// Code generated by grpcgen. DO NOT EDIT.

package quality

import (
	"context"

	"github.com/AndroidGoLab/jni"

	"github.com/AndroidGoLab/jni-proxy/handlestore"
	pb "github.com/AndroidGoLab/jni-proxy/proto/quality"
	"github.com/AndroidGoLab/jni/app"
	jnipkg "github.com/AndroidGoLab/jni/media/quality"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// AmbientBacklightSettingsServer implements pb.AmbientBacklightSettingsServiceServer.
type AmbientBacklightSettingsServer struct {
	pb.UnimplementedAmbientBacklightSettingsServiceServer
	Ctx     *app.Context
	Handles *handlestore.HandleStore
}

func (s *AmbientBacklightSettingsServer) NewAmbientBacklightSettings(_ context.Context, req *pb.NewAmbientBacklightSettingsRequest) (*pb.NewAmbientBacklightSettingsResponse, error) {
	obj, err := jnipkg.NewAmbientBacklightSettings(s.Ctx.VM, req.GetArg0(), req.GetArg1(), req.GetArg2(), req.GetArg3(), req.GetArg4(), req.GetArg5(), req.GetArg6())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create object: %v", err)
	}
	var handle int64
	if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
		handle = s.Handles.Put(env, obj.Obj)
		return nil
	}); doErr != nil {
		return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
	}
	return &pb.NewAmbientBacklightSettingsResponse{Result: handle}, nil
}

func (s *AmbientBacklightSettingsServer) DescribeContents(_ context.Context, req *pb.DescribeContentsRequest) (*pb.DescribeContentsResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightSettings{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.DescribeContents()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.DescribeContentsResponse{Result: result}, nil
}

func (s *AmbientBacklightSettingsServer) GetColorFormat(_ context.Context, req *pb.GetColorFormatRequest) (*pb.GetColorFormatResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightSettings{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetColorFormat()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetColorFormatResponse{Result: result}, nil
}

func (s *AmbientBacklightSettingsServer) GetHorizontalZonesCount(_ context.Context, req *pb.GetHorizontalZonesCountRequest) (*pb.GetHorizontalZonesCountResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightSettings{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetHorizontalZonesCount()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetHorizontalZonesCountResponse{Result: result}, nil
}

func (s *AmbientBacklightSettingsServer) GetMaxFps(_ context.Context, req *pb.GetMaxFpsRequest) (*pb.GetMaxFpsResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightSettings{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetMaxFps()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetMaxFpsResponse{Result: result}, nil
}

func (s *AmbientBacklightSettingsServer) GetSource(_ context.Context, req *pb.GetSourceRequest) (*pb.GetSourceResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightSettings{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetSource()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetSourceResponse{Result: result}, nil
}

func (s *AmbientBacklightSettingsServer) GetThreshold(_ context.Context, req *pb.GetThresholdRequest) (*pb.GetThresholdResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightSettings{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetThreshold()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetThresholdResponse{Result: result}, nil
}

func (s *AmbientBacklightSettingsServer) GetVerticalZonesCount(_ context.Context, req *pb.GetVerticalZonesCountRequest) (*pb.GetVerticalZonesCountResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightSettings{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetVerticalZonesCount()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetVerticalZonesCountResponse{Result: result}, nil
}

func (s *AmbientBacklightSettingsServer) IsLetterboxOmitted(_ context.Context, req *pb.IsLetterboxOmittedRequest) (*pb.IsLetterboxOmittedResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightSettings{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.IsLetterboxOmitted()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsLetterboxOmittedResponse{Result: result}, nil
}

func (s *AmbientBacklightSettingsServer) ToString(_ context.Context, req *pb.ToStringRequest) (*pb.ToStringResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightSettings{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.ToString()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.ToStringResponse{Result: result}, nil
}

func (s *AmbientBacklightSettingsServer) WriteToParcel(_ context.Context, req *pb.WriteToParcelRequest) (*pb.WriteToParcelResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightSettings{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.WriteToParcel(s.Handles.Get(req.GetArg0()), req.GetArg1()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.WriteToParcelResponse{}, nil
}

// AmbientBacklightMetadataServer implements pb.AmbientBacklightMetadataServiceServer.
type AmbientBacklightMetadataServer struct {
	pb.UnimplementedAmbientBacklightMetadataServiceServer
	Ctx     *app.Context
	Handles *handlestore.HandleStore
}

func (s *AmbientBacklightMetadataServer) NewAmbientBacklightMetadata(_ context.Context, req *pb.NewAmbientBacklightMetadataRequest) (*pb.NewAmbientBacklightMetadataResponse, error) {
	obj, err := jnipkg.NewAmbientBacklightMetadata(s.Ctx.VM, req.GetArg0(), req.GetArg1(), req.GetArg2(), req.GetArg3(), req.GetArg4(), req.GetArg5(), s.Handles.Get(req.GetArg6()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create object: %v", err)
	}
	var handle int64
	if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
		handle = s.Handles.Put(env, obj.Obj)
		return nil
	}); doErr != nil {
		return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
	}
	return &pb.NewAmbientBacklightMetadataResponse{Result: handle}, nil
}

func (s *AmbientBacklightMetadataServer) DescribeContents(_ context.Context, req *pb.DescribeContentsRequest) (*pb.DescribeContentsResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightMetadata{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.DescribeContents()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.DescribeContentsResponse{Result: result}, nil
}

func (s *AmbientBacklightMetadataServer) GetColorFormat(_ context.Context, req *pb.GetColorFormatRequest) (*pb.GetColorFormatResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightMetadata{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetColorFormat()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetColorFormatResponse{Result: result}, nil
}

func (s *AmbientBacklightMetadataServer) GetCompressionAlgorithm(_ context.Context, req *pb.GetCompressionAlgorithmRequest) (*pb.GetCompressionAlgorithmResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightMetadata{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetCompressionAlgorithm()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetCompressionAlgorithmResponse{Result: result}, nil
}

func (s *AmbientBacklightMetadataServer) GetHorizontalZonesCount(_ context.Context, req *pb.GetHorizontalZonesCountRequest) (*pb.GetHorizontalZonesCountResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightMetadata{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetHorizontalZonesCount()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetHorizontalZonesCountResponse{Result: result}, nil
}

func (s *AmbientBacklightMetadataServer) GetPackageName(_ context.Context, req *pb.GetPackageNameRequest) (*pb.GetPackageNameResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightMetadata{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetPackageName()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetPackageNameResponse{Result: result}, nil
}

func (s *AmbientBacklightMetadataServer) GetSource(_ context.Context, req *pb.GetSourceRequest) (*pb.GetSourceResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightMetadata{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetSource()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetSourceResponse{Result: result}, nil
}

func (s *AmbientBacklightMetadataServer) GetVerticalZonesCount(_ context.Context, req *pb.GetVerticalZonesCountRequest) (*pb.GetVerticalZonesCountResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightMetadata{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetVerticalZonesCount()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetVerticalZonesCountResponse{Result: result}, nil
}

func (s *AmbientBacklightMetadataServer) GetZoneColors(_ context.Context, req *pb.GetZoneColorsRequest) (*pb.GetZoneColorsResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightMetadata{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetZoneColors()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetZoneColorsResponse{Result: handle}, nil
}

func (s *AmbientBacklightMetadataServer) ToString(_ context.Context, req *pb.ToStringRequest) (*pb.ToStringResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightMetadata{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.ToString()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.ToStringResponse{Result: result}, nil
}

func (s *AmbientBacklightMetadataServer) WriteToParcel(_ context.Context, req *pb.WriteToParcelRequest) (*pb.WriteToParcelResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightMetadata{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.WriteToParcel(s.Handles.Get(req.GetArg0()), req.GetArg1()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.WriteToParcelResponse{}, nil
}

// AmbientBacklightEventServer implements pb.AmbientBacklightEventServiceServer.
type AmbientBacklightEventServer struct {
	pb.UnimplementedAmbientBacklightEventServiceServer
	Ctx     *app.Context
	Handles *handlestore.HandleStore
}

func (s *AmbientBacklightEventServer) NewAmbientBacklightEvent(_ context.Context, req *pb.NewAmbientBacklightEventRequest) (*pb.NewAmbientBacklightEventResponse, error) {
	obj, err := jnipkg.NewAmbientBacklightEvent(s.Ctx.VM, req.GetArg0(), s.Handles.Get(req.GetArg1()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create object: %v", err)
	}
	var handle int64
	if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
		handle = s.Handles.Put(env, obj.Obj)
		return nil
	}); doErr != nil {
		return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
	}
	return &pb.NewAmbientBacklightEventResponse{Result: handle}, nil
}

func (s *AmbientBacklightEventServer) DescribeContents(_ context.Context, req *pb.DescribeContentsRequest) (*pb.DescribeContentsResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightEvent{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.DescribeContents()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.DescribeContentsResponse{Result: result}, nil
}

func (s *AmbientBacklightEventServer) Equals(_ context.Context, req *pb.EqualsRequest) (*pb.EqualsResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightEvent{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.Equals(s.Handles.Get(req.GetArg0()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.EqualsResponse{Result: result}, nil
}

func (s *AmbientBacklightEventServer) GetEventType(_ context.Context, req *pb.GetEventTypeRequest) (*pb.GetEventTypeResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightEvent{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetEventType()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetEventTypeResponse{Result: result}, nil
}

func (s *AmbientBacklightEventServer) GetMetadata(_ context.Context, req *pb.GetMetadataRequest) (*pb.GetMetadataResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightEvent{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetMetadata()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetMetadataResponse{Result: handle}, nil
}

func (s *AmbientBacklightEventServer) HashCode(_ context.Context, req *pb.HashCodeRequest) (*pb.HashCodeResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightEvent{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.HashCode()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.HashCodeResponse{Result: result}, nil
}

func (s *AmbientBacklightEventServer) ToString(_ context.Context, req *pb.ToStringRequest) (*pb.ToStringResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightEvent{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.ToString()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.ToStringResponse{Result: result}, nil
}

func (s *AmbientBacklightEventServer) WriteToParcel(_ context.Context, req *pb.WriteToParcelRequest) (*pb.WriteToParcelResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.AmbientBacklightEvent{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.WriteToParcel(s.Handles.Get(req.GetArg0()), req.GetArg1()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.WriteToParcelResponse{}, nil
}

// ActiveProcessingPictureServer implements pb.ActiveProcessingPictureServiceServer.
type ActiveProcessingPictureServer struct {
	pb.UnimplementedActiveProcessingPictureServiceServer
	Ctx     *app.Context
	Handles *handlestore.HandleStore
}

func (s *ActiveProcessingPictureServer) NewActiveProcessingPicture(_ context.Context, req *pb.NewActiveProcessingPictureRequest) (*pb.NewActiveProcessingPictureResponse, error) {
	obj, err := jnipkg.NewActiveProcessingPicture(s.Ctx.VM, req.GetArg0(), req.GetArg1())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create object: %v", err)
	}
	var handle int64
	if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
		handle = s.Handles.Put(env, obj.Obj)
		return nil
	}); doErr != nil {
		return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
	}
	return &pb.NewActiveProcessingPictureResponse{Result: handle}, nil
}

func (s *ActiveProcessingPictureServer) DescribeContents(_ context.Context, req *pb.DescribeContentsRequest) (*pb.DescribeContentsResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.ActiveProcessingPicture{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.DescribeContents()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.DescribeContentsResponse{Result: result}, nil
}

func (s *ActiveProcessingPictureServer) GetId(_ context.Context, req *pb.GetIdRequest) (*pb.GetIdResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.ActiveProcessingPicture{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetId()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetIdResponse{Result: result}, nil
}

func (s *ActiveProcessingPictureServer) GetProfileId(_ context.Context, req *pb.ActiveProcessingPictureGetProfileIdRequest) (*pb.GetProfileIdResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.ActiveProcessingPicture{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetProfileId()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetProfileIdResponse{Result: result}, nil
}

func (s *ActiveProcessingPictureServer) WriteToParcel(_ context.Context, req *pb.WriteToParcelRequest) (*pb.WriteToParcelResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.ActiveProcessingPicture{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.WriteToParcel(s.Handles.Get(req.GetArg0()), req.GetArg1()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.WriteToParcelResponse{}, nil
}

// MediaQualityManagerServer implements pb.MediaQualityManagerServiceServer.
type MediaQualityManagerServer struct {
	pb.UnimplementedMediaQualityManagerServiceServer
	Ctx     *app.Context
	Handles *handlestore.HandleStore
}

func (s *MediaQualityManagerServer) CreatePictureProfile(_ context.Context, req *pb.CreatePictureProfileRequest) (*pb.CreatePictureProfileResponse, error) {
	mgr, err := jnipkg.NewMediaQualityManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.CreatePictureProfile(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.CreatePictureProfileResponse{}, nil
}

func (s *MediaQualityManagerServer) CreateSoundProfile(_ context.Context, req *pb.CreateSoundProfileRequest) (*pb.CreateSoundProfileResponse, error) {
	mgr, err := jnipkg.NewMediaQualityManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.CreateSoundProfile(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.CreateSoundProfileResponse{}, nil
}

func (s *MediaQualityManagerServer) GetAvailablePictureProfiles(_ context.Context, req *pb.GetAvailablePictureProfilesRequest) (*pb.GetAvailablePictureProfilesResponse, error) {
	mgr, err := jnipkg.NewMediaQualityManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetAvailablePictureProfiles(s.Handles.Get(req.GetArg0()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetAvailablePictureProfilesResponse{Result: handle}, nil
}

func (s *MediaQualityManagerServer) GetAvailableSoundProfiles(_ context.Context, req *pb.GetAvailableSoundProfilesRequest) (*pb.GetAvailableSoundProfilesResponse, error) {
	mgr, err := jnipkg.NewMediaQualityManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetAvailableSoundProfiles(s.Handles.Get(req.GetArg0()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetAvailableSoundProfilesResponse{Result: handle}, nil
}

func (s *MediaQualityManagerServer) GetPictureProfile(_ context.Context, req *pb.GetPictureProfileRequest) (*pb.GetPictureProfileResponse, error) {
	mgr, err := jnipkg.NewMediaQualityManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetPictureProfile(req.GetArg0(), req.GetArg1(), s.Handles.Get(req.GetArg2()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetPictureProfileResponse{Result: handle}, nil
}

func (s *MediaQualityManagerServer) GetSoundProfile(_ context.Context, req *pb.GetSoundProfileRequest) (*pb.GetSoundProfileResponse, error) {
	mgr, err := jnipkg.NewMediaQualityManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetSoundProfile(req.GetArg0(), req.GetArg1(), s.Handles.Get(req.GetArg2()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetSoundProfileResponse{Result: handle}, nil
}

func (s *MediaQualityManagerServer) IsAmbientBacklightEnabled(_ context.Context, req *pb.IsAmbientBacklightEnabledRequest) (*pb.IsAmbientBacklightEnabledResponse, error) {
	mgr, err := jnipkg.NewMediaQualityManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.IsAmbientBacklightEnabled()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsAmbientBacklightEnabledResponse{Result: result}, nil
}

func (s *MediaQualityManagerServer) IsAutoPictureQualityEnabled(_ context.Context, req *pb.IsAutoPictureQualityEnabledRequest) (*pb.IsAutoPictureQualityEnabledResponse, error) {
	mgr, err := jnipkg.NewMediaQualityManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.IsAutoPictureQualityEnabled()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsAutoPictureQualityEnabledResponse{Result: result}, nil
}

func (s *MediaQualityManagerServer) IsAutoSoundQualityEnabled(_ context.Context, req *pb.IsAutoSoundQualityEnabledRequest) (*pb.IsAutoSoundQualityEnabledResponse, error) {
	mgr, err := jnipkg.NewMediaQualityManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.IsAutoSoundQualityEnabled()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsAutoSoundQualityEnabledResponse{Result: result}, nil
}

func (s *MediaQualityManagerServer) IsSuperResolutionEnabled(_ context.Context, req *pb.IsSuperResolutionEnabledRequest) (*pb.IsSuperResolutionEnabledResponse, error) {
	mgr, err := jnipkg.NewMediaQualityManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.IsSuperResolutionEnabled()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsSuperResolutionEnabledResponse{Result: result}, nil
}

func (s *MediaQualityManagerServer) RegisterAmbientBacklightCallback(_ context.Context, req *pb.RegisterAmbientBacklightCallbackRequest) (*pb.RegisterAmbientBacklightCallbackResponse, error) {
	mgr, err := jnipkg.NewMediaQualityManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.RegisterAmbientBacklightCallback(s.Handles.Get(req.GetArg0()), s.Handles.Get(req.GetArg1())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.RegisterAmbientBacklightCallbackResponse{}, nil
}

func (s *MediaQualityManagerServer) RegisterPictureProfileCallback(_ context.Context, req *pb.RegisterPictureProfileCallbackRequest) (*pb.RegisterPictureProfileCallbackResponse, error) {
	mgr, err := jnipkg.NewMediaQualityManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.RegisterPictureProfileCallback(s.Handles.Get(req.GetArg0()), s.Handles.Get(req.GetArg1())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.RegisterPictureProfileCallbackResponse{}, nil
}

func (s *MediaQualityManagerServer) RegisterSoundProfileCallback(_ context.Context, req *pb.RegisterSoundProfileCallbackRequest) (*pb.RegisterSoundProfileCallbackResponse, error) {
	mgr, err := jnipkg.NewMediaQualityManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.RegisterSoundProfileCallback(s.Handles.Get(req.GetArg0()), s.Handles.Get(req.GetArg1())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.RegisterSoundProfileCallbackResponse{}, nil
}

func (s *MediaQualityManagerServer) RemovePictureProfile(_ context.Context, req *pb.RemovePictureProfileRequest) (*pb.RemovePictureProfileResponse, error) {
	mgr, err := jnipkg.NewMediaQualityManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.RemovePictureProfile(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.RemovePictureProfileResponse{}, nil
}

func (s *MediaQualityManagerServer) RemoveSoundProfile(_ context.Context, req *pb.RemoveSoundProfileRequest) (*pb.RemoveSoundProfileResponse, error) {
	mgr, err := jnipkg.NewMediaQualityManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.RemoveSoundProfile(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.RemoveSoundProfileResponse{}, nil
}

func (s *MediaQualityManagerServer) SetAmbientBacklightEnabled(_ context.Context, req *pb.SetAmbientBacklightEnabledRequest) (*pb.SetAmbientBacklightEnabledResponse, error) {
	mgr, err := jnipkg.NewMediaQualityManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.SetAmbientBacklightEnabled(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetAmbientBacklightEnabledResponse{}, nil
}

func (s *MediaQualityManagerServer) SetAmbientBacklightSettings(_ context.Context, req *pb.SetAmbientBacklightSettingsRequest) (*pb.SetAmbientBacklightSettingsResponse, error) {
	mgr, err := jnipkg.NewMediaQualityManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.SetAmbientBacklightSettings(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetAmbientBacklightSettingsResponse{}, nil
}

func (s *MediaQualityManagerServer) UnregisterAmbientBacklightCallback(_ context.Context, req *pb.UnregisterAmbientBacklightCallbackRequest) (*pb.UnregisterAmbientBacklightCallbackResponse, error) {
	mgr, err := jnipkg.NewMediaQualityManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.UnregisterAmbientBacklightCallback(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.UnregisterAmbientBacklightCallbackResponse{}, nil
}

func (s *MediaQualityManagerServer) UnregisterPictureProfileCallback(_ context.Context, req *pb.UnregisterPictureProfileCallbackRequest) (*pb.UnregisterPictureProfileCallbackResponse, error) {
	mgr, err := jnipkg.NewMediaQualityManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.UnregisterPictureProfileCallback(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.UnregisterPictureProfileCallbackResponse{}, nil
}

func (s *MediaQualityManagerServer) UnregisterSoundProfileCallback(_ context.Context, req *pb.UnregisterSoundProfileCallbackRequest) (*pb.UnregisterSoundProfileCallbackResponse, error) {
	mgr, err := jnipkg.NewMediaQualityManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.UnregisterSoundProfileCallback(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.UnregisterSoundProfileCallbackResponse{}, nil
}

func (s *MediaQualityManagerServer) UpdatePictureProfile(_ context.Context, req *pb.UpdatePictureProfileRequest) (*pb.UpdatePictureProfileResponse, error) {
	mgr, err := jnipkg.NewMediaQualityManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.UpdatePictureProfile(req.GetArg0(), s.Handles.Get(req.GetArg1())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.UpdatePictureProfileResponse{}, nil
}

func (s *MediaQualityManagerServer) UpdateSoundProfile(_ context.Context, req *pb.UpdateSoundProfileRequest) (*pb.UpdateSoundProfileResponse, error) {
	mgr, err := jnipkg.NewMediaQualityManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	if err := mgr.UpdateSoundProfile(req.GetArg0(), s.Handles.Get(req.GetArg1())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.UpdateSoundProfileResponse{}, nil
}
