// Code generated by cligen. DO NOT EDIT.

package main

import (
	pb "github.com/AndroidGoLab/jni-proxy/proto/appsetid"
	"github.com/spf13/cobra"
)

var appsetidCmd = &cobra.Command{
	Use:   "appsetid",
	Short: "appsetid service operations",
}

var appsetidAppSetIdManagerCmd = &cobra.Command{
	Use:   "app-set-id-manager",
	Short: "AppSetIdManagerService operations",
}

var appsetidAppSetIdManagerGetCmd = &cobra.Command{
	Use:   "get",
	Short: "Get RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewAppSetIdManagerServiceClient(grpcConn)
		req := &pb.GetRequest{}
		if v, err := cmd.Flags().GetInt64("arg0"); err == nil {
			req.Arg0 = v
		}
		resp, err := client.Get(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var appsetidAppSetIdCmd = &cobra.Command{
	Use:   "app-set-id",
	Short: "AppSetIdService operations",
}

var appsetidAppSetIdNewAppSetIdCmd = &cobra.Command{
	Use:   "new-app-set-id",
	Short: "NewAppSetId RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewAppSetIdServiceClient(grpcConn)
		req := &pb.NewAppSetIdRequest{}
		if v, err := cmd.Flags().GetString("arg0"); err == nil {
			req.Arg0 = v
		}
		if v, err := cmd.Flags().GetInt32("arg1"); err == nil {
			req.Arg1 = v
		}
		resp, err := client.NewAppSetId(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var appsetidAppSetIdEqualsCmd = &cobra.Command{
	Use:   "equals",
	Short: "Equals RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewAppSetIdServiceClient(grpcConn)
		req := &pb.EqualsRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		if v, err := cmd.Flags().GetInt64("arg0"); err == nil {
			req.Arg0 = v
		}
		resp, err := client.Equals(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var appsetidAppSetIdGetIdCmd = &cobra.Command{
	Use:   "get-id",
	Short: "GetId RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewAppSetIdServiceClient(grpcConn)
		req := &pb.GetIdRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		resp, err := client.GetId(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var appsetidAppSetIdGetScopeCmd = &cobra.Command{
	Use:   "get-scope",
	Short: "GetScope RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewAppSetIdServiceClient(grpcConn)
		req := &pb.GetScopeRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		resp, err := client.GetScope(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var appsetidAppSetIdHashCodeCmd = &cobra.Command{
	Use:   "hash-code",
	Short: "HashCode RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewAppSetIdServiceClient(grpcConn)
		req := &pb.HashCodeRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		resp, err := client.HashCode(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

func init() {
	appsetidAppSetIdManagerGetCmd.Flags().Int64("arg0", 0, "arg0 (int64)")
	appsetidAppSetIdManagerCmd.AddCommand(appsetidAppSetIdManagerGetCmd)
	appsetidCmd.AddCommand(appsetidAppSetIdManagerCmd)
	appsetidAppSetIdNewAppSetIdCmd.Flags().String("arg0", "", "arg0 (string)")
	appsetidAppSetIdNewAppSetIdCmd.Flags().Int32("arg1", 0, "arg1 (int32)")
	appsetidAppSetIdCmd.AddCommand(appsetidAppSetIdNewAppSetIdCmd)
	appsetidAppSetIdEqualsCmd.Flags().Int64("handle", 0, "handle (int64)")
	appsetidAppSetIdEqualsCmd.Flags().Int64("arg0", 0, "arg0 (int64)")
	appsetidAppSetIdCmd.AddCommand(appsetidAppSetIdEqualsCmd)
	appsetidAppSetIdGetIdCmd.Flags().Int64("handle", 0, "handle (int64)")
	appsetidAppSetIdCmd.AddCommand(appsetidAppSetIdGetIdCmd)
	appsetidAppSetIdGetScopeCmd.Flags().Int64("handle", 0, "handle (int64)")
	appsetidAppSetIdCmd.AddCommand(appsetidAppSetIdGetScopeCmd)
	appsetidAppSetIdHashCodeCmd.Flags().Int64("handle", 0, "handle (int64)")
	appsetidAppSetIdCmd.AddCommand(appsetidAppSetIdHashCodeCmd)
	appsetidCmd.AddCommand(appsetidAppSetIdCmd)
	rootCmd.AddCommand(appsetidCmd)
}
