// Code generated by cligen. DO NOT EDIT.

package main

import (
	pb "github.com/AndroidGoLab/jni-proxy/proto/jank"
	"github.com/spf13/cobra"
)

var jankCmd = &cobra.Command{
	Use:   "jank",
	Short: "jank service operations",
}

var jankRelativeFrameTimeHistogramCmd = &cobra.Command{
	Use:   "relative-frame-time-histogram",
	Short: "RelativeFrameTimeHistogramService operations",
}

var jankRelativeFrameTimeHistogramNewRelativeFrameTimeHistogramCmd = &cobra.Command{
	Use:   "new-relative-frame-time-histogram",
	Short: "NewRelativeFrameTimeHistogram RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewRelativeFrameTimeHistogramServiceClient(grpcConn)
		req := &pb.NewRelativeFrameTimeHistogramRequest{}
		resp, err := client.NewRelativeFrameTimeHistogram(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var jankRelativeFrameTimeHistogramAddRelativeFrameTimeMillisCmd = &cobra.Command{
	Use:   "add-relative-frame-time-millis",
	Short: "AddRelativeFrameTimeMillis RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewRelativeFrameTimeHistogramServiceClient(grpcConn)
		req := &pb.AddRelativeFrameTimeMillisRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		if v, err := cmd.Flags().GetInt32("arg0"); err == nil {
			req.Arg0 = v
		}
		resp, err := client.AddRelativeFrameTimeMillis(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var jankRelativeFrameTimeHistogramGetBucketCountersCmd = &cobra.Command{
	Use:   "get-bucket-counters",
	Short: "GetBucketCounters RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewRelativeFrameTimeHistogramServiceClient(grpcConn)
		req := &pb.GetBucketCountersRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		resp, err := client.GetBucketCounters(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var jankRelativeFrameTimeHistogramGetBucketEndpointsMillisCmd = &cobra.Command{
	Use:   "get-bucket-endpoints-millis",
	Short: "GetBucketEndpointsMillis RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewRelativeFrameTimeHistogramServiceClient(grpcConn)
		req := &pb.GetBucketEndpointsMillisRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		resp, err := client.GetBucketEndpointsMillis(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var jankAppJankStatsCmd = &cobra.Command{
	Use:   "app-jank-stats",
	Short: "AppJankStatsService operations",
}

var jankAppJankStatsNewAppJankStatsCmd = &cobra.Command{
	Use:   "new-app-jank-stats",
	Short: "NewAppJankStats RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewAppJankStatsServiceClient(grpcConn)
		req := &pb.NewAppJankStatsRequest{}
		if v, err := cmd.Flags().GetInt32("arg0"); err == nil {
			req.Arg0 = v
		}
		if v, err := cmd.Flags().GetString("arg1"); err == nil {
			req.Arg1 = v
		}
		if v, err := cmd.Flags().GetString("arg2"); err == nil {
			req.Arg2 = v
		}
		if v, err := cmd.Flags().GetString("arg3"); err == nil {
			req.Arg3 = v
		}
		if v, err := cmd.Flags().GetString("arg4"); err == nil {
			req.Arg4 = v
		}
		if v, err := cmd.Flags().GetInt64("arg5"); err == nil {
			req.Arg5 = v
		}
		if v, err := cmd.Flags().GetInt64("arg6"); err == nil {
			req.Arg6 = v
		}
		if v, err := cmd.Flags().GetInt64("arg7"); err == nil {
			req.Arg7 = v
		}
		resp, err := client.NewAppJankStats(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var jankAppJankStatsGetJankyFrameCountCmd = &cobra.Command{
	Use:   "get-janky-frame-count",
	Short: "GetJankyFrameCount RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewAppJankStatsServiceClient(grpcConn)
		req := &pb.GetJankyFrameCountRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		resp, err := client.GetJankyFrameCount(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var jankAppJankStatsGetNavigationComponentCmd = &cobra.Command{
	Use:   "get-navigation-component",
	Short: "GetNavigationComponent RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewAppJankStatsServiceClient(grpcConn)
		req := &pb.GetNavigationComponentRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		resp, err := client.GetNavigationComponent(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var jankAppJankStatsGetRelativeFrameTimeHistogramCmd = &cobra.Command{
	Use:   "get-relative-frame-time-histogram",
	Short: "GetRelativeFrameTimeHistogram RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewAppJankStatsServiceClient(grpcConn)
		req := &pb.GetRelativeFrameTimeHistogramRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		resp, err := client.GetRelativeFrameTimeHistogram(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var jankAppJankStatsGetTotalFrameCountCmd = &cobra.Command{
	Use:   "get-total-frame-count",
	Short: "GetTotalFrameCount RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewAppJankStatsServiceClient(grpcConn)
		req := &pb.GetTotalFrameCountRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		resp, err := client.GetTotalFrameCount(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var jankAppJankStatsGetUidCmd = &cobra.Command{
	Use:   "get-uid",
	Short: "GetUid RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewAppJankStatsServiceClient(grpcConn)
		req := &pb.GetUidRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		resp, err := client.GetUid(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var jankAppJankStatsGetWidgetCategoryCmd = &cobra.Command{
	Use:   "get-widget-category",
	Short: "GetWidgetCategory RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewAppJankStatsServiceClient(grpcConn)
		req := &pb.GetWidgetCategoryRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		resp, err := client.GetWidgetCategory(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var jankAppJankStatsGetWidgetIdCmd = &cobra.Command{
	Use:   "get-widget-id",
	Short: "GetWidgetId RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewAppJankStatsServiceClient(grpcConn)
		req := &pb.GetWidgetIdRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		resp, err := client.GetWidgetId(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var jankAppJankStatsGetWidgetStateCmd = &cobra.Command{
	Use:   "get-widget-state",
	Short: "GetWidgetState RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewAppJankStatsServiceClient(grpcConn)
		req := &pb.GetWidgetStateRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		resp, err := client.GetWidgetState(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

func init() {
	jankRelativeFrameTimeHistogramCmd.AddCommand(jankRelativeFrameTimeHistogramNewRelativeFrameTimeHistogramCmd)
	jankRelativeFrameTimeHistogramAddRelativeFrameTimeMillisCmd.Flags().Int64("handle", 0, "handle (int64)")
	jankRelativeFrameTimeHistogramAddRelativeFrameTimeMillisCmd.Flags().Int32("arg0", 0, "arg0 (int32)")
	jankRelativeFrameTimeHistogramCmd.AddCommand(jankRelativeFrameTimeHistogramAddRelativeFrameTimeMillisCmd)
	jankRelativeFrameTimeHistogramGetBucketCountersCmd.Flags().Int64("handle", 0, "handle (int64)")
	jankRelativeFrameTimeHistogramCmd.AddCommand(jankRelativeFrameTimeHistogramGetBucketCountersCmd)
	jankRelativeFrameTimeHistogramGetBucketEndpointsMillisCmd.Flags().Int64("handle", 0, "handle (int64)")
	jankRelativeFrameTimeHistogramCmd.AddCommand(jankRelativeFrameTimeHistogramGetBucketEndpointsMillisCmd)
	jankCmd.AddCommand(jankRelativeFrameTimeHistogramCmd)
	jankAppJankStatsNewAppJankStatsCmd.Flags().Int32("arg0", 0, "arg0 (int32)")
	jankAppJankStatsNewAppJankStatsCmd.Flags().String("arg1", "", "arg1 (string)")
	jankAppJankStatsNewAppJankStatsCmd.Flags().String("arg2", "", "arg2 (string)")
	jankAppJankStatsNewAppJankStatsCmd.Flags().String("arg3", "", "arg3 (string)")
	jankAppJankStatsNewAppJankStatsCmd.Flags().String("arg4", "", "arg4 (string)")
	jankAppJankStatsNewAppJankStatsCmd.Flags().Int64("arg5", 0, "arg5 (int64)")
	jankAppJankStatsNewAppJankStatsCmd.Flags().Int64("arg6", 0, "arg6 (int64)")
	jankAppJankStatsNewAppJankStatsCmd.Flags().Int64("arg7", 0, "arg7 (int64)")
	jankAppJankStatsCmd.AddCommand(jankAppJankStatsNewAppJankStatsCmd)
	jankAppJankStatsGetJankyFrameCountCmd.Flags().Int64("handle", 0, "handle (int64)")
	jankAppJankStatsCmd.AddCommand(jankAppJankStatsGetJankyFrameCountCmd)
	jankAppJankStatsGetNavigationComponentCmd.Flags().Int64("handle", 0, "handle (int64)")
	jankAppJankStatsCmd.AddCommand(jankAppJankStatsGetNavigationComponentCmd)
	jankAppJankStatsGetRelativeFrameTimeHistogramCmd.Flags().Int64("handle", 0, "handle (int64)")
	jankAppJankStatsCmd.AddCommand(jankAppJankStatsGetRelativeFrameTimeHistogramCmd)
	jankAppJankStatsGetTotalFrameCountCmd.Flags().Int64("handle", 0, "handle (int64)")
	jankAppJankStatsCmd.AddCommand(jankAppJankStatsGetTotalFrameCountCmd)
	jankAppJankStatsGetUidCmd.Flags().Int64("handle", 0, "handle (int64)")
	jankAppJankStatsCmd.AddCommand(jankAppJankStatsGetUidCmd)
	jankAppJankStatsGetWidgetCategoryCmd.Flags().Int64("handle", 0, "handle (int64)")
	jankAppJankStatsCmd.AddCommand(jankAppJankStatsGetWidgetCategoryCmd)
	jankAppJankStatsGetWidgetIdCmd.Flags().Int64("handle", 0, "handle (int64)")
	jankAppJankStatsCmd.AddCommand(jankAppJankStatsGetWidgetIdCmd)
	jankAppJankStatsGetWidgetStateCmd.Flags().Int64("handle", 0, "handle (int64)")
	jankAppJankStatsCmd.AddCommand(jankAppJankStatsGetWidgetStateCmd)
	jankCmd.AddCommand(jankAppJankStatsCmd)
	rootCmd.AddCommand(jankCmd)
}
