// Code generated by cligen. DO NOT EDIT.

package main

import (
	pb "github.com/AndroidGoLab/jni-proxy/proto/topics"
	"github.com/spf13/cobra"
)

var topicsCmd = &cobra.Command{
	Use:   "topics",
	Short: "topics service operations",
}

var topicsEncryptedTopicCmd = &cobra.Command{
	Use:   "encrypted-topic",
	Short: "EncryptedTopicService operations",
}

var topicsEncryptedTopicNewEncryptedTopicCmd = &cobra.Command{
	Use:   "new-encrypted-topic",
	Short: "NewEncryptedTopic RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewEncryptedTopicServiceClient(grpcConn)
		req := &pb.NewEncryptedTopicRequest{}
		if v, err := cmd.Flags().GetInt64("arg0"); err == nil {
			req.Arg0 = v
		}
		if v, err := cmd.Flags().GetString("arg1"); err == nil {
			req.Arg1 = v
		}
		if v, err := cmd.Flags().GetInt64("arg2"); err == nil {
			req.Arg2 = v
		}
		resp, err := client.NewEncryptedTopic(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var topicsEncryptedTopicEqualsCmd = &cobra.Command{
	Use:   "equals",
	Short: "Equals RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewEncryptedTopicServiceClient(grpcConn)
		req := &pb.EqualsRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		if v, err := cmd.Flags().GetInt64("arg0"); err == nil {
			req.Arg0 = v
		}
		resp, err := client.Equals(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var topicsEncryptedTopicGetEncapsulatedKeyCmd = &cobra.Command{
	Use:   "get-encapsulated-key",
	Short: "GetEncapsulatedKey RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewEncryptedTopicServiceClient(grpcConn)
		req := &pb.GetEncapsulatedKeyRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		resp, err := client.GetEncapsulatedKey(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var topicsEncryptedTopicGetEncryptedTopicCmd = &cobra.Command{
	Use:   "get-encrypted-topic",
	Short: "GetEncryptedTopic RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewEncryptedTopicServiceClient(grpcConn)
		req := &pb.GetEncryptedTopicRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		resp, err := client.GetEncryptedTopic(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var topicsEncryptedTopicGetKeyIdentifierCmd = &cobra.Command{
	Use:   "get-key-identifier",
	Short: "GetKeyIdentifier RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewEncryptedTopicServiceClient(grpcConn)
		req := &pb.GetKeyIdentifierRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		resp, err := client.GetKeyIdentifier(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var topicsEncryptedTopicHashCodeCmd = &cobra.Command{
	Use:   "hash-code",
	Short: "HashCode RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewEncryptedTopicServiceClient(grpcConn)
		req := &pb.HashCodeRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		resp, err := client.HashCode(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var topicsEncryptedTopicToStringCmd = &cobra.Command{
	Use:   "to-string",
	Short: "ToString RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewEncryptedTopicServiceClient(grpcConn)
		req := &pb.ToStringRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		resp, err := client.ToString(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var topicsManagerCmd = &cobra.Command{
	Use:   "manager",
	Short: "ManagerService operations",
}

var topicsManagerGetCmd = &cobra.Command{
	Use:   "get",
	Short: "Get RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewManagerServiceClient(grpcConn)
		req := &pb.GetRequest{}
		if v, err := cmd.Flags().GetInt64("arg0"); err == nil {
			req.Arg0 = v
		}
		resp, err := client.Get(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var topicsTopicCmd = &cobra.Command{
	Use:   "topic",
	Short: "TopicService operations",
}

var topicsTopicNewTopicCmd = &cobra.Command{
	Use:   "new-topic",
	Short: "NewTopic RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewTopicServiceClient(grpcConn)
		req := &pb.NewTopicRequest{}
		if v, err := cmd.Flags().GetInt64("arg0"); err == nil {
			req.Arg0 = v
		}
		if v, err := cmd.Flags().GetInt64("arg1"); err == nil {
			req.Arg1 = v
		}
		if v, err := cmd.Flags().GetInt32("arg2"); err == nil {
			req.Arg2 = v
		}
		resp, err := client.NewTopic(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var topicsTopicEqualsCmd = &cobra.Command{
	Use:   "equals",
	Short: "Equals RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewTopicServiceClient(grpcConn)
		req := &pb.EqualsRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		if v, err := cmd.Flags().GetInt64("arg0"); err == nil {
			req.Arg0 = v
		}
		resp, err := client.Equals(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var topicsTopicGetModelVersionCmd = &cobra.Command{
	Use:   "get-model-version",
	Short: "GetModelVersion RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewTopicServiceClient(grpcConn)
		req := &pb.GetModelVersionRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		resp, err := client.GetModelVersion(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var topicsTopicGetTaxonomyVersionCmd = &cobra.Command{
	Use:   "get-taxonomy-version",
	Short: "GetTaxonomyVersion RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewTopicServiceClient(grpcConn)
		req := &pb.GetTaxonomyVersionRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		resp, err := client.GetTaxonomyVersion(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var topicsTopicGetTopicIdCmd = &cobra.Command{
	Use:   "get-topic-id",
	Short: "GetTopicId RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewTopicServiceClient(grpcConn)
		req := &pb.GetTopicIdRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		resp, err := client.GetTopicId(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var topicsTopicHashCodeCmd = &cobra.Command{
	Use:   "hash-code",
	Short: "HashCode RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewTopicServiceClient(grpcConn)
		req := &pb.HashCodeRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		resp, err := client.HashCode(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var topicsTopicToStringCmd = &cobra.Command{
	Use:   "to-string",
	Short: "ToString RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewTopicServiceClient(grpcConn)
		req := &pb.ToStringRequest{}
		if v, err := cmd.Flags().GetInt64("handle"); err == nil {
			req.Handle = v
		}
		resp, err := client.ToString(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var topicsGetTopicsResponseCmd = &cobra.Command{
	Use:   "get-topics-response",
	Short: "GetTopicsResponseService operations",
}

var topicsGetTopicsResponseEqualsCmd = &cobra.Command{
	Use:   "equals",
	Short: "Equals RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewGetTopicsResponseServiceClient(grpcConn)
		req := &pb.GetTopicsResponseEqualsRequest{}
		if v, err := cmd.Flags().GetInt64("arg0"); err == nil {
			req.Arg0 = v
		}
		resp, err := client.Equals(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var topicsGetTopicsResponseGetEncryptedTopicsCmd = &cobra.Command{
	Use:   "get-encrypted-topics",
	Short: "GetEncryptedTopics RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewGetTopicsResponseServiceClient(grpcConn)
		req := &pb.GetEncryptedTopicsRequest{}
		resp, err := client.GetEncryptedTopics(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var topicsGetTopicsResponseGetTopicsCmd = &cobra.Command{
	Use:   "get-topics",
	Short: "GetTopics RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewGetTopicsResponseServiceClient(grpcConn)
		req := &pb.GetTopicsRequest{}
		resp, err := client.GetTopics(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var topicsGetTopicsResponseHashCodeCmd = &cobra.Command{
	Use:   "hash-code",
	Short: "HashCode RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewGetTopicsResponseServiceClient(grpcConn)
		req := &pb.GetTopicsResponseHashCodeRequest{}
		resp, err := client.HashCode(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var topicsGetTopicsResponseBuilderCmd = &cobra.Command{
	Use:   "get-topics-response-builder",
	Short: "GetTopicsResponseBuilderService operations",
}

var topicsGetTopicsResponseBuilderBuildCmd = &cobra.Command{
	Use:   "build",
	Short: "Build RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewGetTopicsResponseBuilderServiceClient(grpcConn)
		req := &pb.BuildRequest{}
		resp, err := client.Build(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var topicsGetTopicsRequestCmd = &cobra.Command{
	Use:   "get-topics-request",
	Short: "GetTopicsRequestService operations",
}

var topicsGetTopicsRequestGetAdsSdkNameCmd = &cobra.Command{
	Use:   "get-ads-sdk-name",
	Short: "GetAdsSdkName RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewGetTopicsRequestServiceClient(grpcConn)
		req := &pb.GetAdsSdkNameRequest{}
		resp, err := client.GetAdsSdkName(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var topicsGetTopicsRequestShouldRecordObservationCmd = &cobra.Command{
	Use:   "should-record-observation",
	Short: "ShouldRecordObservation RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewGetTopicsRequestServiceClient(grpcConn)
		req := &pb.ShouldRecordObservationRequest{}
		resp, err := client.ShouldRecordObservation(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var topicsGetTopicsRequestBuilderCmd = &cobra.Command{
	Use:   "get-topics-request-builder",
	Short: "GetTopicsRequestBuilderService operations",
}

var topicsGetTopicsRequestBuilderBuildCmd = &cobra.Command{
	Use:   "build",
	Short: "Build RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewGetTopicsRequestBuilderServiceClient(grpcConn)
		req := &pb.BuildRequest{}
		resp, err := client.Build(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var topicsGetTopicsRequestBuilderSetAdsSdkNameCmd = &cobra.Command{
	Use:   "set-ads-sdk-name",
	Short: "SetAdsSdkName RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewGetTopicsRequestBuilderServiceClient(grpcConn)
		req := &pb.SetAdsSdkNameRequest{}
		if v, err := cmd.Flags().GetString("arg0"); err == nil {
			req.Arg0 = v
		}
		resp, err := client.SetAdsSdkName(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var topicsGetTopicsRequestBuilderSetShouldRecordObservationCmd = &cobra.Command{
	Use:   "set-should-record-observation",
	Short: "SetShouldRecordObservation RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewGetTopicsRequestBuilderServiceClient(grpcConn)
		req := &pb.SetShouldRecordObservationRequest{}
		if v, err := cmd.Flags().GetBool("arg0"); err == nil {
			req.Arg0 = v
		}
		resp, err := client.SetShouldRecordObservation(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

func init() {
	topicsEncryptedTopicNewEncryptedTopicCmd.Flags().Int64("arg0", 0, "arg0 (int64)")
	topicsEncryptedTopicNewEncryptedTopicCmd.Flags().String("arg1", "", "arg1 (string)")
	topicsEncryptedTopicNewEncryptedTopicCmd.Flags().Int64("arg2", 0, "arg2 (int64)")
	topicsEncryptedTopicCmd.AddCommand(topicsEncryptedTopicNewEncryptedTopicCmd)
	topicsEncryptedTopicEqualsCmd.Flags().Int64("handle", 0, "handle (int64)")
	topicsEncryptedTopicEqualsCmd.Flags().Int64("arg0", 0, "arg0 (int64)")
	topicsEncryptedTopicCmd.AddCommand(topicsEncryptedTopicEqualsCmd)
	topicsEncryptedTopicGetEncapsulatedKeyCmd.Flags().Int64("handle", 0, "handle (int64)")
	topicsEncryptedTopicCmd.AddCommand(topicsEncryptedTopicGetEncapsulatedKeyCmd)
	topicsEncryptedTopicGetEncryptedTopicCmd.Flags().Int64("handle", 0, "handle (int64)")
	topicsEncryptedTopicCmd.AddCommand(topicsEncryptedTopicGetEncryptedTopicCmd)
	topicsEncryptedTopicGetKeyIdentifierCmd.Flags().Int64("handle", 0, "handle (int64)")
	topicsEncryptedTopicCmd.AddCommand(topicsEncryptedTopicGetKeyIdentifierCmd)
	topicsEncryptedTopicHashCodeCmd.Flags().Int64("handle", 0, "handle (int64)")
	topicsEncryptedTopicCmd.AddCommand(topicsEncryptedTopicHashCodeCmd)
	topicsEncryptedTopicToStringCmd.Flags().Int64("handle", 0, "handle (int64)")
	topicsEncryptedTopicCmd.AddCommand(topicsEncryptedTopicToStringCmd)
	topicsCmd.AddCommand(topicsEncryptedTopicCmd)
	topicsManagerGetCmd.Flags().Int64("arg0", 0, "arg0 (int64)")
	topicsManagerCmd.AddCommand(topicsManagerGetCmd)
	topicsCmd.AddCommand(topicsManagerCmd)
	topicsTopicNewTopicCmd.Flags().Int64("arg0", 0, "arg0 (int64)")
	topicsTopicNewTopicCmd.Flags().Int64("arg1", 0, "arg1 (int64)")
	topicsTopicNewTopicCmd.Flags().Int32("arg2", 0, "arg2 (int32)")
	topicsTopicCmd.AddCommand(topicsTopicNewTopicCmd)
	topicsTopicEqualsCmd.Flags().Int64("handle", 0, "handle (int64)")
	topicsTopicEqualsCmd.Flags().Int64("arg0", 0, "arg0 (int64)")
	topicsTopicCmd.AddCommand(topicsTopicEqualsCmd)
	topicsTopicGetModelVersionCmd.Flags().Int64("handle", 0, "handle (int64)")
	topicsTopicCmd.AddCommand(topicsTopicGetModelVersionCmd)
	topicsTopicGetTaxonomyVersionCmd.Flags().Int64("handle", 0, "handle (int64)")
	topicsTopicCmd.AddCommand(topicsTopicGetTaxonomyVersionCmd)
	topicsTopicGetTopicIdCmd.Flags().Int64("handle", 0, "handle (int64)")
	topicsTopicCmd.AddCommand(topicsTopicGetTopicIdCmd)
	topicsTopicHashCodeCmd.Flags().Int64("handle", 0, "handle (int64)")
	topicsTopicCmd.AddCommand(topicsTopicHashCodeCmd)
	topicsTopicToStringCmd.Flags().Int64("handle", 0, "handle (int64)")
	topicsTopicCmd.AddCommand(topicsTopicToStringCmd)
	topicsCmd.AddCommand(topicsTopicCmd)
	topicsGetTopicsResponseEqualsCmd.Flags().Int64("arg0", 0, "arg0 (int64)")
	topicsGetTopicsResponseCmd.AddCommand(topicsGetTopicsResponseEqualsCmd)
	topicsGetTopicsResponseCmd.AddCommand(topicsGetTopicsResponseGetEncryptedTopicsCmd)
	topicsGetTopicsResponseCmd.AddCommand(topicsGetTopicsResponseGetTopicsCmd)
	topicsGetTopicsResponseCmd.AddCommand(topicsGetTopicsResponseHashCodeCmd)
	topicsCmd.AddCommand(topicsGetTopicsResponseCmd)
	topicsGetTopicsResponseBuilderCmd.AddCommand(topicsGetTopicsResponseBuilderBuildCmd)
	topicsCmd.AddCommand(topicsGetTopicsResponseBuilderCmd)
	topicsGetTopicsRequestCmd.AddCommand(topicsGetTopicsRequestGetAdsSdkNameCmd)
	topicsGetTopicsRequestCmd.AddCommand(topicsGetTopicsRequestShouldRecordObservationCmd)
	topicsCmd.AddCommand(topicsGetTopicsRequestCmd)
	topicsGetTopicsRequestBuilderCmd.AddCommand(topicsGetTopicsRequestBuilderBuildCmd)
	topicsGetTopicsRequestBuilderSetAdsSdkNameCmd.Flags().String("arg0", "", "arg0 (string)")
	topicsGetTopicsRequestBuilderCmd.AddCommand(topicsGetTopicsRequestBuilderSetAdsSdkNameCmd)
	topicsGetTopicsRequestBuilderSetShouldRecordObservationCmd.Flags().Bool("arg0", false, "arg0 (bool)")
	topicsGetTopicsRequestBuilderCmd.AddCommand(topicsGetTopicsRequestBuilderSetShouldRecordObservationCmd)
	topicsCmd.AddCommand(topicsGetTopicsRequestBuilderCmd)
	rootCmd.AddCommand(topicsCmd)
}
