// Code generated by cligen. DO NOT EDIT.

package main

import (
	pb "github.com/AndroidGoLab/jni-proxy/proto/vibrator"
	"github.com/spf13/cobra"
)

var vibratorCmd = &cobra.Command{
	Use:   "vibrator",
	Short: "vibrator service operations",
}

var vibratorVibratorCmd = &cobra.Command{
	Use:   "vibrator",
	Short: "VibratorService operations",
}

var vibratorVibratorAreAllEffectsSupportedCmd = &cobra.Command{
	Use:   "are-all-effects-supported",
	Short: "AreAllEffectsSupported RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewVibratorServiceClient(grpcConn)
		req := &pb.AreAllEffectsSupportedRequest{}
		if v, err := cmd.Flags().GetInt64("arg0"); err == nil {
			req.Arg0 = v
		}
		resp, err := client.AreAllEffectsSupported(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorVibratorAreAllPrimitivesSupportedCmd = &cobra.Command{
	Use:   "are-all-primitives-supported",
	Short: "AreAllPrimitivesSupported RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewVibratorServiceClient(grpcConn)
		req := &pb.AreAllPrimitivesSupportedRequest{}
		if v, err := cmd.Flags().GetInt64("arg0"); err == nil {
			req.Arg0 = v
		}
		resp, err := client.AreAllPrimitivesSupported(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorVibratorAreEffectsSupportedCmd = &cobra.Command{
	Use:   "are-effects-supported",
	Short: "AreEffectsSupported RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewVibratorServiceClient(grpcConn)
		req := &pb.AreEffectsSupportedRequest{}
		if v, err := cmd.Flags().GetInt64("arg0"); err == nil {
			req.Arg0 = v
		}
		resp, err := client.AreEffectsSupported(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorVibratorAreEnvelopeEffectsSupportedCmd = &cobra.Command{
	Use:   "are-envelope-effects-supported",
	Short: "AreEnvelopeEffectsSupported RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewVibratorServiceClient(grpcConn)
		req := &pb.AreEnvelopeEffectsSupportedRequest{}
		resp, err := client.AreEnvelopeEffectsSupported(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorVibratorArePrimitivesSupportedCmd = &cobra.Command{
	Use:   "are-primitives-supported",
	Short: "ArePrimitivesSupported RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewVibratorServiceClient(grpcConn)
		req := &pb.ArePrimitivesSupportedRequest{}
		if v, err := cmd.Flags().GetInt64("arg0"); err == nil {
			req.Arg0 = v
		}
		resp, err := client.ArePrimitivesSupported(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorVibratorCancelCmd = &cobra.Command{
	Use:   "cancel",
	Short: "Cancel RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewVibratorServiceClient(grpcConn)
		req := &pb.CancelRequest{}
		resp, err := client.Cancel(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorVibratorGetEnvelopeEffectInfoCmd = &cobra.Command{
	Use:   "get-envelope-effect-info",
	Short: "GetEnvelopeEffectInfo RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewVibratorServiceClient(grpcConn)
		req := &pb.GetEnvelopeEffectInfoRequest{}
		resp, err := client.GetEnvelopeEffectInfo(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorVibratorGetFrequencyProfileCmd = &cobra.Command{
	Use:   "get-frequency-profile",
	Short: "GetFrequencyProfile RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewVibratorServiceClient(grpcConn)
		req := &pb.GetFrequencyProfileRequest{}
		resp, err := client.GetFrequencyProfile(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorVibratorGetIdCmd = &cobra.Command{
	Use:   "get-id",
	Short: "GetId RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewVibratorServiceClient(grpcConn)
		req := &pb.GetIdRequest{}
		resp, err := client.GetId(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorVibratorGetPrimitiveDurationsCmd = &cobra.Command{
	Use:   "get-primitive-durations",
	Short: "GetPrimitiveDurations RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewVibratorServiceClient(grpcConn)
		req := &pb.GetPrimitiveDurationsRequest{}
		if v, err := cmd.Flags().GetInt64("arg0"); err == nil {
			req.Arg0 = v
		}
		resp, err := client.GetPrimitiveDurations(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorVibratorGetQFactorCmd = &cobra.Command{
	Use:   "get-q-factor",
	Short: "GetQFactor RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewVibratorServiceClient(grpcConn)
		req := &pb.GetQFactorRequest{}
		resp, err := client.GetQFactor(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorVibratorGetResonantFrequencyCmd = &cobra.Command{
	Use:   "get-resonant-frequency",
	Short: "GetResonantFrequency RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewVibratorServiceClient(grpcConn)
		req := &pb.GetResonantFrequencyRequest{}
		resp, err := client.GetResonantFrequency(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorVibratorHasAmplitudeControlCmd = &cobra.Command{
	Use:   "has-amplitude-control",
	Short: "HasAmplitudeControl RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewVibratorServiceClient(grpcConn)
		req := &pb.HasAmplitudeControlRequest{}
		resp, err := client.HasAmplitudeControl(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorVibratorHasVibratorCmd = &cobra.Command{
	Use:   "has-vibrator",
	Short: "HasVibrator RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewVibratorServiceClient(grpcConn)
		req := &pb.HasVibratorRequest{}
		resp, err := client.HasVibrator(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorVibratorVibrate1Cmd = &cobra.Command{
	Use:   "vibrate1",
	Short: "Vibrate1 RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewVibratorServiceClient(grpcConn)
		req := &pb.Vibrate1Request{}
		if v, err := cmd.Flags().GetInt64("arg0"); err == nil {
			req.Arg0 = v
		}
		resp, err := client.Vibrate1(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorVibratorVibrate2_1Cmd = &cobra.Command{
	Use:   "vibrate2_1",
	Short: "Vibrate2_1 RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewVibratorServiceClient(grpcConn)
		req := &pb.Vibrate2_1Request{}
		if v, err := cmd.Flags().GetInt64("arg0"); err == nil {
			req.Arg0 = v
		}
		if v, err := cmd.Flags().GetInt64("arg1"); err == nil {
			req.Arg1 = v
		}
		resp, err := client.Vibrate2_1(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorVibratorVibrate2_2Cmd = &cobra.Command{
	Use:   "vibrate2_2",
	Short: "Vibrate2_2 RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewVibratorServiceClient(grpcConn)
		req := &pb.Vibrate2_2Request{}
		if v, err := cmd.Flags().GetInt64("arg0"); err == nil {
			req.Arg0 = v
		}
		if v, err := cmd.Flags().GetInt64("arg1"); err == nil {
			req.Arg1 = v
		}
		resp, err := client.Vibrate2_2(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorVibratorVibrate1_3Cmd = &cobra.Command{
	Use:   "vibrate1_3",
	Short: "Vibrate1_3 RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewVibratorServiceClient(grpcConn)
		req := &pb.Vibrate1_3Request{}
		if v, err := cmd.Flags().GetInt64("arg0"); err == nil {
			req.Arg0 = v
		}
		resp, err := client.Vibrate1_3(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorVibratorVibrate2_4Cmd = &cobra.Command{
	Use:   "vibrate2_4",
	Short: "Vibrate2_4 RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewVibratorServiceClient(grpcConn)
		req := &pb.Vibrate2_4Request{}
		if v, err := cmd.Flags().GetInt64("arg0"); err == nil {
			req.Arg0 = v
		}
		if v, err := cmd.Flags().GetInt64("arg1"); err == nil {
			req.Arg1 = v
		}
		resp, err := client.Vibrate2_4(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorVibratorVibrate2_5Cmd = &cobra.Command{
	Use:   "vibrate2_5",
	Short: "Vibrate2_5 RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewVibratorServiceClient(grpcConn)
		req := &pb.Vibrate2_5Request{}
		if v, err := cmd.Flags().GetInt64("arg0"); err == nil {
			req.Arg0 = v
		}
		if v, err := cmd.Flags().GetInt32("arg1"); err == nil {
			req.Arg1 = v
		}
		resp, err := client.Vibrate2_5(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorVibratorVibrate3_6Cmd = &cobra.Command{
	Use:   "vibrate3_6",
	Short: "Vibrate3_6 RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewVibratorServiceClient(grpcConn)
		req := &pb.Vibrate3_6Request{}
		if v, err := cmd.Flags().GetInt64("arg0"); err == nil {
			req.Arg0 = v
		}
		if v, err := cmd.Flags().GetInt32("arg1"); err == nil {
			req.Arg1 = v
		}
		if v, err := cmd.Flags().GetInt64("arg2"); err == nil {
			req.Arg2 = v
		}
		resp, err := client.Vibrate3_6(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorEnvelopeEffectInfoCmd = &cobra.Command{
	Use:   "envelope-effect-info",
	Short: "EnvelopeEffectInfoService operations",
}

var vibratorEnvelopeEffectInfoDescribeContentsCmd = &cobra.Command{
	Use:   "describe-contents",
	Short: "DescribeContents RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewEnvelopeEffectInfoServiceClient(grpcConn)
		req := &pb.DescribeContentsRequest{}
		resp, err := client.DescribeContents(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorEnvelopeEffectInfoEqualsCmd = &cobra.Command{
	Use:   "equals",
	Short: "Equals RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewEnvelopeEffectInfoServiceClient(grpcConn)
		req := &pb.EqualsRequest{}
		if v, err := cmd.Flags().GetInt64("arg0"); err == nil {
			req.Arg0 = v
		}
		resp, err := client.Equals(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorEnvelopeEffectInfoGetMaxControlPointDurationMillisCmd = &cobra.Command{
	Use:   "get-max-control-point-duration-millis",
	Short: "GetMaxControlPointDurationMillis RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewEnvelopeEffectInfoServiceClient(grpcConn)
		req := &pb.GetMaxControlPointDurationMillisRequest{}
		resp, err := client.GetMaxControlPointDurationMillis(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorEnvelopeEffectInfoGetMaxDurationMillisCmd = &cobra.Command{
	Use:   "get-max-duration-millis",
	Short: "GetMaxDurationMillis RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewEnvelopeEffectInfoServiceClient(grpcConn)
		req := &pb.GetMaxDurationMillisRequest{}
		resp, err := client.GetMaxDurationMillis(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorEnvelopeEffectInfoGetMaxSizeCmd = &cobra.Command{
	Use:   "get-max-size",
	Short: "GetMaxSize RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewEnvelopeEffectInfoServiceClient(grpcConn)
		req := &pb.GetMaxSizeRequest{}
		resp, err := client.GetMaxSize(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorEnvelopeEffectInfoGetMinControlPointDurationMillisCmd = &cobra.Command{
	Use:   "get-min-control-point-duration-millis",
	Short: "GetMinControlPointDurationMillis RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewEnvelopeEffectInfoServiceClient(grpcConn)
		req := &pb.GetMinControlPointDurationMillisRequest{}
		resp, err := client.GetMinControlPointDurationMillis(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorEnvelopeEffectInfoHashCodeCmd = &cobra.Command{
	Use:   "hash-code",
	Short: "HashCode RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewEnvelopeEffectInfoServiceClient(grpcConn)
		req := &pb.HashCodeRequest{}
		resp, err := client.HashCode(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorEnvelopeEffectInfoToStringCmd = &cobra.Command{
	Use:   "to-string",
	Short: "ToString RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewEnvelopeEffectInfoServiceClient(grpcConn)
		req := &pb.ToStringRequest{}
		resp, err := client.ToString(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorEnvelopeEffectInfoWriteToParcelCmd = &cobra.Command{
	Use:   "write-to-parcel",
	Short: "WriteToParcel RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewEnvelopeEffectInfoServiceClient(grpcConn)
		req := &pb.WriteToParcelRequest{}
		if v, err := cmd.Flags().GetInt64("arg0"); err == nil {
			req.Arg0 = v
		}
		if v, err := cmd.Flags().GetInt32("arg1"); err == nil {
			req.Arg1 = v
		}
		resp, err := client.WriteToParcel(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorFrequencyProfileCmd = &cobra.Command{
	Use:   "frequency-profile",
	Short: "FrequencyProfileService operations",
}

var vibratorFrequencyProfileGetMaxFrequencyHzCmd = &cobra.Command{
	Use:   "get-max-frequency-hz",
	Short: "GetMaxFrequencyHz RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewFrequencyProfileServiceClient(grpcConn)
		req := &pb.GetMaxFrequencyHzRequest{}
		resp, err := client.GetMaxFrequencyHz(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorFrequencyProfileGetMaxOutputAccelerationGsCmd = &cobra.Command{
	Use:   "get-max-output-acceleration-gs",
	Short: "GetMaxOutputAccelerationGs RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewFrequencyProfileServiceClient(grpcConn)
		req := &pb.GetMaxOutputAccelerationGsRequest{}
		resp, err := client.GetMaxOutputAccelerationGs(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorFrequencyProfileGetMinFrequencyHzCmd = &cobra.Command{
	Use:   "get-min-frequency-hz",
	Short: "GetMinFrequencyHz RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewFrequencyProfileServiceClient(grpcConn)
		req := &pb.GetMinFrequencyHzRequest{}
		resp, err := client.GetMinFrequencyHz(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

var vibratorFrequencyProfileGetOutputAccelerationGsCmd = &cobra.Command{
	Use:   "get-output-acceleration-gs",
	Short: "GetOutputAccelerationGs RPC",
	RunE: func(cmd *cobra.Command, args []string) error {
		ctx, cancel := requestContext(cmd)
		defer cancel()
		client := pb.NewFrequencyProfileServiceClient(grpcConn)
		req := &pb.GetOutputAccelerationGsRequest{}
		if v, err := cmd.Flags().GetFloat32("arg0"); err == nil {
			req.Arg0 = v
		}
		resp, err := client.GetOutputAccelerationGs(ctx, req)
		if err != nil {
			return err
		}
		return printProtoMessage(resp)
	},
}

func init() {
	vibratorVibratorAreAllEffectsSupportedCmd.Flags().Int64("arg0", 0, "arg0 (int64)")
	vibratorVibratorCmd.AddCommand(vibratorVibratorAreAllEffectsSupportedCmd)
	vibratorVibratorAreAllPrimitivesSupportedCmd.Flags().Int64("arg0", 0, "arg0 (int64)")
	vibratorVibratorCmd.AddCommand(vibratorVibratorAreAllPrimitivesSupportedCmd)
	vibratorVibratorAreEffectsSupportedCmd.Flags().Int64("arg0", 0, "arg0 (int64)")
	vibratorVibratorCmd.AddCommand(vibratorVibratorAreEffectsSupportedCmd)
	vibratorVibratorCmd.AddCommand(vibratorVibratorAreEnvelopeEffectsSupportedCmd)
	vibratorVibratorArePrimitivesSupportedCmd.Flags().Int64("arg0", 0, "arg0 (int64)")
	vibratorVibratorCmd.AddCommand(vibratorVibratorArePrimitivesSupportedCmd)
	vibratorVibratorCmd.AddCommand(vibratorVibratorCancelCmd)
	vibratorVibratorCmd.AddCommand(vibratorVibratorGetEnvelopeEffectInfoCmd)
	vibratorVibratorCmd.AddCommand(vibratorVibratorGetFrequencyProfileCmd)
	vibratorVibratorCmd.AddCommand(vibratorVibratorGetIdCmd)
	vibratorVibratorGetPrimitiveDurationsCmd.Flags().Int64("arg0", 0, "arg0 (int64)")
	vibratorVibratorCmd.AddCommand(vibratorVibratorGetPrimitiveDurationsCmd)
	vibratorVibratorCmd.AddCommand(vibratorVibratorGetQFactorCmd)
	vibratorVibratorCmd.AddCommand(vibratorVibratorGetResonantFrequencyCmd)
	vibratorVibratorCmd.AddCommand(vibratorVibratorHasAmplitudeControlCmd)
	vibratorVibratorCmd.AddCommand(vibratorVibratorHasVibratorCmd)
	vibratorVibratorVibrate1Cmd.Flags().Int64("arg0", 0, "arg0 (int64)")
	vibratorVibratorCmd.AddCommand(vibratorVibratorVibrate1Cmd)
	vibratorVibratorVibrate2_1Cmd.Flags().Int64("arg0", 0, "arg0 (int64)")
	vibratorVibratorVibrate2_1Cmd.Flags().Int64("arg1", 0, "arg1 (int64)")
	vibratorVibratorCmd.AddCommand(vibratorVibratorVibrate2_1Cmd)
	vibratorVibratorVibrate2_2Cmd.Flags().Int64("arg0", 0, "arg0 (int64)")
	vibratorVibratorVibrate2_2Cmd.Flags().Int64("arg1", 0, "arg1 (int64)")
	vibratorVibratorCmd.AddCommand(vibratorVibratorVibrate2_2Cmd)
	vibratorVibratorVibrate1_3Cmd.Flags().Int64("arg0", 0, "arg0 (int64)")
	vibratorVibratorCmd.AddCommand(vibratorVibratorVibrate1_3Cmd)
	vibratorVibratorVibrate2_4Cmd.Flags().Int64("arg0", 0, "arg0 (int64)")
	vibratorVibratorVibrate2_4Cmd.Flags().Int64("arg1", 0, "arg1 (int64)")
	vibratorVibratorCmd.AddCommand(vibratorVibratorVibrate2_4Cmd)
	vibratorVibratorVibrate2_5Cmd.Flags().Int64("arg0", 0, "arg0 (int64)")
	vibratorVibratorVibrate2_5Cmd.Flags().Int32("arg1", 0, "arg1 (int32)")
	vibratorVibratorCmd.AddCommand(vibratorVibratorVibrate2_5Cmd)
	vibratorVibratorVibrate3_6Cmd.Flags().Int64("arg0", 0, "arg0 (int64)")
	vibratorVibratorVibrate3_6Cmd.Flags().Int32("arg1", 0, "arg1 (int32)")
	vibratorVibratorVibrate3_6Cmd.Flags().Int64("arg2", 0, "arg2 (int64)")
	vibratorVibratorCmd.AddCommand(vibratorVibratorVibrate3_6Cmd)
	vibratorCmd.AddCommand(vibratorVibratorCmd)
	vibratorEnvelopeEffectInfoCmd.AddCommand(vibratorEnvelopeEffectInfoDescribeContentsCmd)
	vibratorEnvelopeEffectInfoEqualsCmd.Flags().Int64("arg0", 0, "arg0 (int64)")
	vibratorEnvelopeEffectInfoCmd.AddCommand(vibratorEnvelopeEffectInfoEqualsCmd)
	vibratorEnvelopeEffectInfoCmd.AddCommand(vibratorEnvelopeEffectInfoGetMaxControlPointDurationMillisCmd)
	vibratorEnvelopeEffectInfoCmd.AddCommand(vibratorEnvelopeEffectInfoGetMaxDurationMillisCmd)
	vibratorEnvelopeEffectInfoCmd.AddCommand(vibratorEnvelopeEffectInfoGetMaxSizeCmd)
	vibratorEnvelopeEffectInfoCmd.AddCommand(vibratorEnvelopeEffectInfoGetMinControlPointDurationMillisCmd)
	vibratorEnvelopeEffectInfoCmd.AddCommand(vibratorEnvelopeEffectInfoHashCodeCmd)
	vibratorEnvelopeEffectInfoCmd.AddCommand(vibratorEnvelopeEffectInfoToStringCmd)
	vibratorEnvelopeEffectInfoWriteToParcelCmd.Flags().Int64("arg0", 0, "arg0 (int64)")
	vibratorEnvelopeEffectInfoWriteToParcelCmd.Flags().Int32("arg1", 0, "arg1 (int32)")
	vibratorEnvelopeEffectInfoCmd.AddCommand(vibratorEnvelopeEffectInfoWriteToParcelCmd)
	vibratorCmd.AddCommand(vibratorEnvelopeEffectInfoCmd)
	vibratorFrequencyProfileCmd.AddCommand(vibratorFrequencyProfileGetMaxFrequencyHzCmd)
	vibratorFrequencyProfileCmd.AddCommand(vibratorFrequencyProfileGetMaxOutputAccelerationGsCmd)
	vibratorFrequencyProfileCmd.AddCommand(vibratorFrequencyProfileGetMinFrequencyHzCmd)
	vibratorFrequencyProfileGetOutputAccelerationGsCmd.Flags().Float32("arg0", 0, "arg0 (float32)")
	vibratorFrequencyProfileCmd.AddCommand(vibratorFrequencyProfileGetOutputAccelerationGsCmd)
	vibratorCmd.AddCommand(vibratorFrequencyProfileCmd)
	rootCmd.AddCommand(vibratorCmd)
}
