// Code generated by grpcgen. DO NOT EDIT.

package usage

import (
	"context"

	"github.com/AndroidGoLab/jni"

	"github.com/AndroidGoLab/jni-proxy/handlestore"
	pb "github.com/AndroidGoLab/jni-proxy/proto/usage"
	"github.com/AndroidGoLab/jni/app"
	jnipkg "github.com/AndroidGoLab/jni/app/usage"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// StatsManagerServer implements pb.StatsManagerServiceServer.
type StatsManagerServer struct {
	pb.UnimplementedStatsManagerServiceServer
	Ctx     *app.Context
	Handles *handlestore.HandleStore
}

func (s *StatsManagerServer) GetAppStandbyBucket(_ context.Context, req *pb.GetAppStandbyBucketRequest) (*pb.GetAppStandbyBucketResponse, error) {
	mgr, err := jnipkg.NewStatsManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.GetAppStandbyBucket()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetAppStandbyBucketResponse{Result: result}, nil
}

func (s *StatsManagerServer) IsAppInactive(_ context.Context, req *pb.IsAppInactiveRequest) (*pb.IsAppInactiveResponse, error) {
	mgr, err := jnipkg.NewStatsManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.IsAppInactive(req.GetArg0())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsAppInactiveResponse{Result: result}, nil
}

func (s *StatsManagerServer) QueryConfigurations(_ context.Context, req *pb.QueryConfigurationsRequest) (*pb.QueryConfigurationsResponse, error) {
	mgr, err := jnipkg.NewStatsManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.QueryConfigurations(req.GetArg0(), req.GetArg1(), req.GetArg2())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.QueryConfigurationsResponse{Result: handle}, nil
}

func (s *StatsManagerServer) QueryEventStats(_ context.Context, req *pb.QueryEventStatsRequest) (*pb.QueryEventStatsResponse, error) {
	mgr, err := jnipkg.NewStatsManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.QueryEventStats(req.GetArg0(), req.GetArg1(), req.GetArg2())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.QueryEventStatsResponse{Result: handle}, nil
}

func (s *StatsManagerServer) QueryEvents1(_ context.Context, req *pb.QueryEvents1Request) (*pb.QueryEvents1Response, error) {
	mgr, err := jnipkg.NewStatsManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.QueryEvents1(s.Handles.Get(req.GetArg0()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.QueryEvents1Response{Result: handle}, nil
}

func (s *StatsManagerServer) QueryEvents2_1(_ context.Context, req *pb.QueryEvents2_1Request) (*pb.QueryEvents2_1Response, error) {
	mgr, err := jnipkg.NewStatsManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.QueryEvents2_1(req.GetArg0(), req.GetArg1())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.QueryEvents2_1Response{Result: handle}, nil
}

func (s *StatsManagerServer) QueryEventsForSelf(_ context.Context, req *pb.QueryEventsForSelfRequest) (*pb.QueryEventsForSelfResponse, error) {
	mgr, err := jnipkg.NewStatsManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.QueryEventsForSelf(req.GetArg0(), req.GetArg1())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.QueryEventsForSelfResponse{Result: handle}, nil
}

func (s *StatsManagerServer) QueryUsageStats(_ context.Context, req *pb.QueryUsageStatsRequest) (*pb.QueryUsageStatsResponse, error) {
	mgr, err := jnipkg.NewStatsManager(s.Ctx)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create manager: %v", err)
	}
	defer mgr.Close()

	result, err := mgr.QueryUsageStats(req.GetArg0(), req.GetArg1(), req.GetArg2())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.QueryUsageStatsResponse{Result: handle}, nil
}
