// Code generated by grpcgen. DO NOT EDIT.

package clipboard

import (
	"context"

	pb "github.com/AndroidGoLab/jni-proxy/proto/clipboard"
	"google.golang.org/grpc"
)

// Client wraps the gRPC ManagerService client.
type Client struct {
	cc  grpc.ClientConnInterface
	svc pb.ManagerServiceClient
}

// NewClient creates a new clipboard client.
func NewClient(cc grpc.ClientConnInterface) *Client {
	return &Client{
		cc:  cc,
		svc: pb.NewManagerServiceClient(cc),
	}
}

// AddPrimaryClipChangedListener calls the AddPrimaryClipChangedListener RPC.
func (c *Client) AddPrimaryClipChangedListener(ctx context.Context, arg0 int64) error {
	_, err := c.svc.AddPrimaryClipChangedListener(ctx, &pb.AddPrimaryClipChangedListenerRequest{
		Arg0: arg0,
	})
	return err
}

// ClearPrimaryClip calls the ClearPrimaryClip RPC.
func (c *Client) ClearPrimaryClip(ctx context.Context) error {
	_, err := c.svc.ClearPrimaryClip(ctx, &pb.ClearPrimaryClipRequest{})
	return err
}

// GetPrimaryClip calls the GetPrimaryClip RPC.
func (c *Client) GetPrimaryClip(ctx context.Context) (int64, error) {
	resp, err := c.svc.GetPrimaryClip(ctx, &pb.GetPrimaryClipRequest{})
	if err != nil {
		return 0, err
	}
	return resp.GetResult(), nil
}

// GetPrimaryClipDescription calls the GetPrimaryClipDescription RPC.
func (c *Client) GetPrimaryClipDescription(ctx context.Context) (int64, error) {
	resp, err := c.svc.GetPrimaryClipDescription(ctx, &pb.GetPrimaryClipDescriptionRequest{})
	if err != nil {
		return 0, err
	}
	return resp.GetResult(), nil
}

// GetText calls the GetText RPC.
func (c *Client) GetText(ctx context.Context) (string, error) {
	resp, err := c.svc.GetText(ctx, &pb.GetTextRequest{})
	if err != nil {
		return "", err
	}
	return resp.GetResult(), nil
}

// HasPrimaryClip calls the HasPrimaryClip RPC.
func (c *Client) HasPrimaryClip(ctx context.Context) (bool, error) {
	resp, err := c.svc.HasPrimaryClip(ctx, &pb.HasPrimaryClipRequest{})
	if err != nil {
		return false, err
	}
	return resp.GetResult(), nil
}

// HasText calls the HasText RPC.
func (c *Client) HasText(ctx context.Context) (bool, error) {
	resp, err := c.svc.HasText(ctx, &pb.HasTextRequest{})
	if err != nil {
		return false, err
	}
	return resp.GetResult(), nil
}

// RemovePrimaryClipChangedListener calls the RemovePrimaryClipChangedListener RPC.
func (c *Client) RemovePrimaryClipChangedListener(ctx context.Context, arg0 int64) error {
	_, err := c.svc.RemovePrimaryClipChangedListener(ctx, &pb.RemovePrimaryClipChangedListenerRequest{
		Arg0: arg0,
	})
	return err
}

// SetPrimaryClip calls the SetPrimaryClip RPC.
func (c *Client) SetPrimaryClip(ctx context.Context, arg0 int64) error {
	_, err := c.svc.SetPrimaryClip(ctx, &pb.SetPrimaryClipRequest{
		Arg0: arg0,
	})
	return err
}

// SetText calls the SetText RPC.
func (c *Client) SetText(ctx context.Context, arg0 string) error {
	_, err := c.svc.SetText(ctx, &pb.SetTextRequest{
		Arg0: arg0,
	})
	return err
}
