// Code generated by grpcgen. DO NOT EDIT.

package common

import (
	"context"

	"github.com/AndroidGoLab/jni"

	"github.com/AndroidGoLab/jni-proxy/handlestore"
	pb "github.com/AndroidGoLab/jni-proxy/proto/common"
	jnipkg "github.com/AndroidGoLab/jni/adservices/common"
	"github.com/AndroidGoLab/jni/app"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// ComponentAdDataServer implements pb.ComponentAdDataServiceServer.
type ComponentAdDataServer struct {
	pb.UnimplementedComponentAdDataServiceServer
	Ctx     *app.Context
	Handles *handlestore.HandleStore
}

func (s *ComponentAdDataServer) NewComponentAdData(_ context.Context, req *pb.NewComponentAdDataRequest) (*pb.NewComponentAdDataResponse, error) {
	obj, err := jnipkg.NewComponentAdData(s.Ctx.VM, s.Handles.Get(req.GetArg0()), req.GetArg1())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create object: %v", err)
	}
	var handle int64
	if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
		handle = s.Handles.Put(env, obj.Obj)
		return nil
	}); doErr != nil {
		return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
	}
	return &pb.NewComponentAdDataResponse{Result: handle}, nil
}

func (s *ComponentAdDataServer) DescribeContents(_ context.Context, req *pb.ComponentAdDataDescribeContentsRequest) (*pb.DescribeContentsResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.ComponentAdData{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.DescribeContents()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.DescribeContentsResponse{Result: result}, nil
}

func (s *ComponentAdDataServer) Equals(_ context.Context, req *pb.ComponentAdDataEqualsRequest) (*pb.EqualsResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.ComponentAdData{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.Equals(s.Handles.Get(req.GetArg0()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.EqualsResponse{Result: result}, nil
}

func (s *ComponentAdDataServer) GetAdRenderId(_ context.Context, req *pb.GetAdRenderIdRequest) (*pb.GetAdRenderIdResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.ComponentAdData{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetAdRenderId()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetAdRenderIdResponse{Result: result}, nil
}

func (s *ComponentAdDataServer) GetRenderUri(_ context.Context, req *pb.GetRenderUriRequest) (*pb.GetRenderUriResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.ComponentAdData{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetRenderUri()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetRenderUriResponse{Result: handle}, nil
}

func (s *ComponentAdDataServer) HashCode(_ context.Context, req *pb.ComponentAdDataHashCodeRequest) (*pb.HashCodeResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.ComponentAdData{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.HashCode()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.HashCodeResponse{Result: result}, nil
}

func (s *ComponentAdDataServer) ToString(_ context.Context, req *pb.ComponentAdDataToStringRequest) (*pb.ToStringResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.ComponentAdData{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.ToString()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.ToStringResponse{Result: result}, nil
}

func (s *ComponentAdDataServer) WriteToParcel(_ context.Context, req *pb.ComponentAdDataWriteToParcelRequest) (*pb.WriteToParcelResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.ComponentAdData{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.WriteToParcel(s.Handles.Get(req.GetArg0()), req.GetArg1()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.WriteToParcelResponse{}, nil
}
