// Code generated by grpcgen. DO NOT EDIT.

package cardemulation

import (
	"context"

	pb "github.com/AndroidGoLab/jni-proxy/proto/cardemulation"
	"google.golang.org/grpc"
)

// HostApduServiceClient wraps the gRPC HostApduServiceService client.
type HostApduServiceClient struct {
	svc pb.HostApduServiceServiceClient
}

// NewHostApduServiceClient creates a new HostApduService client.
func NewHostApduServiceClient(cc grpc.ClientConnInterface) *HostApduServiceClient {
	return &HostApduServiceClient{
		svc: pb.NewHostApduServiceServiceClient(cc),
	}
}

// NotifyUnhandled calls the NotifyUnhandled RPC.
func (c *HostApduServiceClient) NotifyUnhandled(ctx context.Context) error {
	_, err := c.svc.NotifyUnhandled(ctx, &pb.NotifyUnhandledRequest{})
	return err
}

// OnBind calls the OnBind RPC.
func (c *HostApduServiceClient) OnBind(ctx context.Context, arg0 int64) (int64, error) {
	resp, err := c.svc.OnBind(ctx, &pb.OnBindRequest{
		Arg0: arg0,
	})
	if err != nil {
		return 0, err
	}
	return resp.GetResult(), nil
}

// OnDeactivated calls the OnDeactivated RPC.
func (c *HostApduServiceClient) OnDeactivated(ctx context.Context, arg0 int32) error {
	_, err := c.svc.OnDeactivated(ctx, &pb.OnDeactivatedRequest{
		Arg0: arg0,
	})
	return err
}

// ProcessCommandApdu calls the ProcessCommandApdu RPC.
func (c *HostApduServiceClient) ProcessCommandApdu(ctx context.Context, arg0 int64, arg1 int64) (int64, error) {
	resp, err := c.svc.ProcessCommandApdu(ctx, &pb.ProcessCommandApduRequest{
		Arg0: arg0,
		Arg1: arg1,
	})
	if err != nil {
		return 0, err
	}
	return resp.GetResult(), nil
}

// SendResponseApdu calls the SendResponseApdu RPC.
func (c *HostApduServiceClient) SendResponseApdu(ctx context.Context, arg0 int64) error {
	_, err := c.svc.SendResponseApdu(ctx, &pb.SendResponseApduRequest{
		Arg0: arg0,
	})
	return err
}

// PollingFrameClient wraps the gRPC PollingFrameService client.
type PollingFrameClient struct {
	svc pb.PollingFrameServiceClient
}

// NewPollingFrameClient creates a new PollingFrame client.
func NewPollingFrameClient(cc grpc.ClientConnInterface) *PollingFrameClient {
	return &PollingFrameClient{
		svc: pb.NewPollingFrameServiceClient(cc),
	}
}

// DescribeContents calls the DescribeContents RPC.
func (c *PollingFrameClient) DescribeContents(ctx context.Context) (int32, error) {
	resp, err := c.svc.DescribeContents(ctx, &pb.DescribeContentsRequest{})
	if err != nil {
		return 0, err
	}
	return resp.GetResult(), nil
}

// GetData calls the GetData RPC.
func (c *PollingFrameClient) GetData(ctx context.Context) (int64, error) {
	resp, err := c.svc.GetData(ctx, &pb.GetDataRequest{})
	if err != nil {
		return 0, err
	}
	return resp.GetResult(), nil
}

// GetTimestamp calls the GetTimestamp RPC.
func (c *PollingFrameClient) GetTimestamp(ctx context.Context) (int64, error) {
	resp, err := c.svc.GetTimestamp(ctx, &pb.GetTimestampRequest{})
	if err != nil {
		return 0, err
	}
	return resp.GetResult(), nil
}

// GetTriggeredAutoTransact calls the GetTriggeredAutoTransact RPC.
func (c *PollingFrameClient) GetTriggeredAutoTransact(ctx context.Context) (bool, error) {
	resp, err := c.svc.GetTriggeredAutoTransact(ctx, &pb.GetTriggeredAutoTransactRequest{})
	if err != nil {
		return false, err
	}
	return resp.GetResult(), nil
}

// GetType calls the GetType RPC.
func (c *PollingFrameClient) GetType(ctx context.Context) (int32, error) {
	resp, err := c.svc.GetType(ctx, &pb.GetTypeRequest{})
	if err != nil {
		return 0, err
	}
	return resp.GetResult(), nil
}

// GetVendorSpecificGain calls the GetVendorSpecificGain RPC.
func (c *PollingFrameClient) GetVendorSpecificGain(ctx context.Context) (int32, error) {
	resp, err := c.svc.GetVendorSpecificGain(ctx, &pb.GetVendorSpecificGainRequest{})
	if err != nil {
		return 0, err
	}
	return resp.GetResult(), nil
}

// ToString calls the ToString RPC.
func (c *PollingFrameClient) ToString(ctx context.Context) (string, error) {
	resp, err := c.svc.ToString(ctx, &pb.ToStringRequest{})
	if err != nil {
		return "", err
	}
	return resp.GetResult(), nil
}

// WriteToParcel calls the WriteToParcel RPC.
func (c *PollingFrameClient) WriteToParcel(ctx context.Context, arg0 int64, arg1 int32) error {
	_, err := c.svc.WriteToParcel(ctx, &pb.WriteToParcelRequest{
		Arg0: arg0,
		Arg1: arg1,
	})
	return err
}

// HostNfcFServiceClient wraps the gRPC HostNfcFServiceService client.
type HostNfcFServiceClient struct {
	svc pb.HostNfcFServiceServiceClient
}

// NewHostNfcFServiceClient creates a new HostNfcFService client.
func NewHostNfcFServiceClient(cc grpc.ClientConnInterface) *HostNfcFServiceClient {
	return &HostNfcFServiceClient{
		svc: pb.NewHostNfcFServiceServiceClient(cc),
	}
}

// OnBind calls the OnBind RPC.
func (c *HostNfcFServiceClient) OnBind(ctx context.Context, arg0 int64) (int64, error) {
	resp, err := c.svc.OnBind(ctx, &pb.OnBindRequest{
		Arg0: arg0,
	})
	if err != nil {
		return 0, err
	}
	return resp.GetResult(), nil
}

// OnDeactivated calls the OnDeactivated RPC.
func (c *HostNfcFServiceClient) OnDeactivated(ctx context.Context, arg0 int32) error {
	_, err := c.svc.OnDeactivated(ctx, &pb.OnDeactivatedRequest{
		Arg0: arg0,
	})
	return err
}

// ProcessNfcFPacket calls the ProcessNfcFPacket RPC.
func (c *HostNfcFServiceClient) ProcessNfcFPacket(ctx context.Context, arg0 int64, arg1 int64) (int64, error) {
	resp, err := c.svc.ProcessNfcFPacket(ctx, &pb.ProcessNfcFPacketRequest{
		Arg0: arg0,
		Arg1: arg1,
	})
	if err != nil {
		return 0, err
	}
	return resp.GetResult(), nil
}

// SendResponsePacket calls the SendResponsePacket RPC.
func (c *HostNfcFServiceClient) SendResponsePacket(ctx context.Context, arg0 int64) error {
	_, err := c.svc.SendResponsePacket(ctx, &pb.SendResponsePacketRequest{
		Arg0: arg0,
	})
	return err
}

// OffHostApduServiceClient wraps the gRPC OffHostApduServiceService client.
type OffHostApduServiceClient struct {
	svc pb.OffHostApduServiceServiceClient
}

// NewOffHostApduServiceClient creates a new OffHostApduService client.
func NewOffHostApduServiceClient(cc grpc.ClientConnInterface) *OffHostApduServiceClient {
	return &OffHostApduServiceClient{
		svc: pb.NewOffHostApduServiceServiceClient(cc),
	}
}

// OnBind calls the OnBind RPC.
func (c *OffHostApduServiceClient) OnBind(ctx context.Context, arg0 int64) (int64, error) {
	resp, err := c.svc.OnBind(ctx, &pb.OnBindRequest{
		Arg0: arg0,
	})
	if err != nil {
		return 0, err
	}
	return resp.GetResult(), nil
}

// CardEmulationClient wraps the gRPC CardEmulationService client.
type CardEmulationClient struct {
	svc pb.CardEmulationServiceClient
}

// NewCardEmulationClient creates a new CardEmulation client.
func NewCardEmulationClient(cc grpc.ClientConnInterface) *CardEmulationClient {
	return &CardEmulationClient{
		svc: pb.NewCardEmulationServiceClient(cc),
	}
}

// CategoryAllowsForegroundPreference calls the CategoryAllowsForegroundPreference RPC.
func (c *CardEmulationClient) CategoryAllowsForegroundPreference(ctx context.Context, arg0 string) (bool, error) {
	resp, err := c.svc.CategoryAllowsForegroundPreference(ctx, &pb.CategoryAllowsForegroundPreferenceRequest{
		Arg0: arg0,
	})
	if err != nil {
		return false, err
	}
	return resp.GetResult(), nil
}

// GetDefaultNfcSubscriptionId calls the GetDefaultNfcSubscriptionId RPC.
func (c *CardEmulationClient) GetDefaultNfcSubscriptionId(ctx context.Context) (int32, error) {
	resp, err := c.svc.GetDefaultNfcSubscriptionId(ctx, &pb.GetDefaultNfcSubscriptionIdRequest{})
	if err != nil {
		return 0, err
	}
	return resp.GetResult(), nil
}

// GetDescriptionForPreferredPaymentService calls the GetDescriptionForPreferredPaymentService RPC.
func (c *CardEmulationClient) GetDescriptionForPreferredPaymentService(ctx context.Context) (int64, error) {
	resp, err := c.svc.GetDescriptionForPreferredPaymentService(ctx, &pb.GetDescriptionForPreferredPaymentServiceRequest{})
	if err != nil {
		return 0, err
	}
	return resp.GetResult(), nil
}

// GetRouteDestinationForPreferredPaymentService calls the GetRouteDestinationForPreferredPaymentService RPC.
func (c *CardEmulationClient) GetRouteDestinationForPreferredPaymentService(ctx context.Context) (string, error) {
	resp, err := c.svc.GetRouteDestinationForPreferredPaymentService(ctx, &pb.GetRouteDestinationForPreferredPaymentServiceRequest{})
	if err != nil {
		return "", err
	}
	return resp.GetResult(), nil
}

// GetSelectionModeForCategory calls the GetSelectionModeForCategory RPC.
func (c *CardEmulationClient) GetSelectionModeForCategory(ctx context.Context, arg0 string) (int32, error) {
	resp, err := c.svc.GetSelectionModeForCategory(ctx, &pb.GetSelectionModeForCategoryRequest{
		Arg0: arg0,
	})
	if err != nil {
		return 0, err
	}
	return resp.GetResult(), nil
}

// IsDefaultServiceForAid calls the IsDefaultServiceForAid RPC.
func (c *CardEmulationClient) IsDefaultServiceForAid(ctx context.Context, arg0 int64, arg1 string) (bool, error) {
	resp, err := c.svc.IsDefaultServiceForAid(ctx, &pb.IsDefaultServiceForAidRequest{
		Arg0: arg0,
		Arg1: arg1,
	})
	if err != nil {
		return false, err
	}
	return resp.GetResult(), nil
}

// IsDefaultServiceForCategory calls the IsDefaultServiceForCategory RPC.
func (c *CardEmulationClient) IsDefaultServiceForCategory(ctx context.Context, arg0 int64, arg1 string) (bool, error) {
	resp, err := c.svc.IsDefaultServiceForCategory(ctx, &pb.IsDefaultServiceForCategoryRequest{
		Arg0: arg0,
		Arg1: arg1,
	})
	if err != nil {
		return false, err
	}
	return resp.GetResult(), nil
}

// IsEuiccSupported calls the IsEuiccSupported RPC.
func (c *CardEmulationClient) IsEuiccSupported(ctx context.Context) (bool, error) {
	resp, err := c.svc.IsEuiccSupported(ctx, &pb.IsEuiccSupportedRequest{})
	if err != nil {
		return false, err
	}
	return resp.GetResult(), nil
}

// RegisterNfcEventCallback calls the RegisterNfcEventCallback RPC.
func (c *CardEmulationClient) RegisterNfcEventCallback(ctx context.Context, arg0 int64, arg1 int64) error {
	_, err := c.svc.RegisterNfcEventCallback(ctx, &pb.RegisterNfcEventCallbackRequest{
		Arg0: arg0,
		Arg1: arg1,
	})
	return err
}

// RegisterPollingLoopFilterForService calls the RegisterPollingLoopFilterForService RPC.
func (c *CardEmulationClient) RegisterPollingLoopFilterForService(ctx context.Context, arg0 int64, arg1 string, arg2 bool) (bool, error) {
	resp, err := c.svc.RegisterPollingLoopFilterForService(ctx, &pb.RegisterPollingLoopFilterForServiceRequest{
		Arg0: arg0,
		Arg1: arg1,
		Arg2: arg2,
	})
	if err != nil {
		return false, err
	}
	return resp.GetResult(), nil
}

// RegisterPollingLoopPatternFilterForService calls the RegisterPollingLoopPatternFilterForService RPC.
func (c *CardEmulationClient) RegisterPollingLoopPatternFilterForService(ctx context.Context, arg0 int64, arg1 string, arg2 bool) (bool, error) {
	resp, err := c.svc.RegisterPollingLoopPatternFilterForService(ctx, &pb.RegisterPollingLoopPatternFilterForServiceRequest{
		Arg0: arg0,
		Arg1: arg1,
		Arg2: arg2,
	})
	if err != nil {
		return false, err
	}
	return resp.GetResult(), nil
}

// RemoveAidsForService calls the RemoveAidsForService RPC.
func (c *CardEmulationClient) RemoveAidsForService(ctx context.Context, arg0 int64, arg1 string) (bool, error) {
	resp, err := c.svc.RemoveAidsForService(ctx, &pb.RemoveAidsForServiceRequest{
		Arg0: arg0,
		Arg1: arg1,
	})
	if err != nil {
		return false, err
	}
	return resp.GetResult(), nil
}

// RemovePollingLoopFilterForService calls the RemovePollingLoopFilterForService RPC.
func (c *CardEmulationClient) RemovePollingLoopFilterForService(ctx context.Context, arg0 int64, arg1 string) (bool, error) {
	resp, err := c.svc.RemovePollingLoopFilterForService(ctx, &pb.RemovePollingLoopFilterForServiceRequest{
		Arg0: arg0,
		Arg1: arg1,
	})
	if err != nil {
		return false, err
	}
	return resp.GetResult(), nil
}

// RemovePollingLoopPatternFilterForService calls the RemovePollingLoopPatternFilterForService RPC.
func (c *CardEmulationClient) RemovePollingLoopPatternFilterForService(ctx context.Context, arg0 int64, arg1 string) (bool, error) {
	resp, err := c.svc.RemovePollingLoopPatternFilterForService(ctx, &pb.RemovePollingLoopPatternFilterForServiceRequest{
		Arg0: arg0,
		Arg1: arg1,
	})
	if err != nil {
		return false, err
	}
	return resp.GetResult(), nil
}

// SetOffHostForService calls the SetOffHostForService RPC.
func (c *CardEmulationClient) SetOffHostForService(ctx context.Context, arg0 int64, arg1 string) (bool, error) {
	resp, err := c.svc.SetOffHostForService(ctx, &pb.SetOffHostForServiceRequest{
		Arg0: arg0,
		Arg1: arg1,
	})
	if err != nil {
		return false, err
	}
	return resp.GetResult(), nil
}

// SetPreferredService calls the SetPreferredService RPC.
func (c *CardEmulationClient) SetPreferredService(ctx context.Context, arg0 int64, arg1 int64) (bool, error) {
	resp, err := c.svc.SetPreferredService(ctx, &pb.SetPreferredServiceRequest{
		Arg0: arg0,
		Arg1: arg1,
	})
	if err != nil {
		return false, err
	}
	return resp.GetResult(), nil
}

// SetShouldDefaultToObserveModeForService calls the SetShouldDefaultToObserveModeForService RPC.
func (c *CardEmulationClient) SetShouldDefaultToObserveModeForService(ctx context.Context, arg0 int64, arg1 bool) (bool, error) {
	resp, err := c.svc.SetShouldDefaultToObserveModeForService(ctx, &pb.SetShouldDefaultToObserveModeForServiceRequest{
		Arg0: arg0,
		Arg1: arg1,
	})
	if err != nil {
		return false, err
	}
	return resp.GetResult(), nil
}

// SupportsAidPrefixRegistration calls the SupportsAidPrefixRegistration RPC.
func (c *CardEmulationClient) SupportsAidPrefixRegistration(ctx context.Context) (bool, error) {
	resp, err := c.svc.SupportsAidPrefixRegistration(ctx, &pb.SupportsAidPrefixRegistrationRequest{})
	if err != nil {
		return false, err
	}
	return resp.GetResult(), nil
}

// UnregisterNfcEventCallback calls the UnregisterNfcEventCallback RPC.
func (c *CardEmulationClient) UnregisterNfcEventCallback(ctx context.Context, arg0 int64) error {
	_, err := c.svc.UnregisterNfcEventCallback(ctx, &pb.UnregisterNfcEventCallbackRequest{
		Arg0: arg0,
	})
	return err
}

// UnsetOffHostForService calls the UnsetOffHostForService RPC.
func (c *CardEmulationClient) UnsetOffHostForService(ctx context.Context, arg0 int64) (bool, error) {
	resp, err := c.svc.UnsetOffHostForService(ctx, &pb.UnsetOffHostForServiceRequest{
		Arg0: arg0,
	})
	if err != nil {
		return false, err
	}
	return resp.GetResult(), nil
}

// UnsetPreferredService calls the UnsetPreferredService RPC.
func (c *CardEmulationClient) UnsetPreferredService(ctx context.Context, arg0 int64) (bool, error) {
	resp, err := c.svc.UnsetPreferredService(ctx, &pb.UnsetPreferredServiceRequest{
		Arg0: arg0,
	})
	if err != nil {
		return false, err
	}
	return resp.GetResult(), nil
}

// NfcFCardEmulationClient wraps the gRPC NfcFCardEmulationService client.
type NfcFCardEmulationClient struct {
	svc pb.NfcFCardEmulationServiceClient
}

// NewNfcFCardEmulationClient creates a new NfcFCardEmulation client.
func NewNfcFCardEmulationClient(cc grpc.ClientConnInterface) *NfcFCardEmulationClient {
	return &NfcFCardEmulationClient{
		svc: pb.NewNfcFCardEmulationServiceClient(cc),
	}
}

// DisableService calls the DisableService RPC.
func (c *NfcFCardEmulationClient) DisableService(ctx context.Context, arg0 int64) (bool, error) {
	resp, err := c.svc.DisableService(ctx, &pb.DisableServiceRequest{
		Arg0: arg0,
	})
	if err != nil {
		return false, err
	}
	return resp.GetResult(), nil
}

// EnableService calls the EnableService RPC.
func (c *NfcFCardEmulationClient) EnableService(ctx context.Context, arg0 int64, arg1 int64) (bool, error) {
	resp, err := c.svc.EnableService(ctx, &pb.EnableServiceRequest{
		Arg0: arg0,
		Arg1: arg1,
	})
	if err != nil {
		return false, err
	}
	return resp.GetResult(), nil
}

// GetNfcid2ForService calls the GetNfcid2ForService RPC.
func (c *NfcFCardEmulationClient) GetNfcid2ForService(ctx context.Context, arg0 int64) (string, error) {
	resp, err := c.svc.GetNfcid2ForService(ctx, &pb.GetNfcid2ForServiceRequest{
		Arg0: arg0,
	})
	if err != nil {
		return "", err
	}
	return resp.GetResult(), nil
}

// GetSystemCodeForService calls the GetSystemCodeForService RPC.
func (c *NfcFCardEmulationClient) GetSystemCodeForService(ctx context.Context, arg0 int64) (string, error) {
	resp, err := c.svc.GetSystemCodeForService(ctx, &pb.GetSystemCodeForServiceRequest{
		Arg0: arg0,
	})
	if err != nil {
		return "", err
	}
	return resp.GetResult(), nil
}

// RegisterSystemCodeForService calls the RegisterSystemCodeForService RPC.
func (c *NfcFCardEmulationClient) RegisterSystemCodeForService(ctx context.Context, arg0 int64, arg1 string) (bool, error) {
	resp, err := c.svc.RegisterSystemCodeForService(ctx, &pb.RegisterSystemCodeForServiceRequest{
		Arg0: arg0,
		Arg1: arg1,
	})
	if err != nil {
		return false, err
	}
	return resp.GetResult(), nil
}

// SetNfcid2ForService calls the SetNfcid2ForService RPC.
func (c *NfcFCardEmulationClient) SetNfcid2ForService(ctx context.Context, arg0 int64, arg1 string) (bool, error) {
	resp, err := c.svc.SetNfcid2ForService(ctx, &pb.SetNfcid2ForServiceRequest{
		Arg0: arg0,
		Arg1: arg1,
	})
	if err != nil {
		return false, err
	}
	return resp.GetResult(), nil
}

// UnregisterSystemCodeForService calls the UnregisterSystemCodeForService RPC.
func (c *NfcFCardEmulationClient) UnregisterSystemCodeForService(ctx context.Context, arg0 int64) (bool, error) {
	resp, err := c.svc.UnregisterSystemCodeForService(ctx, &pb.UnregisterSystemCodeForServiceRequest{
		Arg0: arg0,
	})
	if err != nil {
		return false, err
	}
	return resp.GetResult(), nil
}
