// Code generated by protogen. DO NOT EDIT.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/textservice/textservice.proto

package textservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TextServicesManagerService_GetCurrentSpellCheckerInfo_FullMethodName = "/textservice.TextServicesManagerService/GetCurrentSpellCheckerInfo"
	TextServicesManagerService_IsSpellCheckerEnabled_FullMethodName      = "/textservice.TextServicesManagerService/IsSpellCheckerEnabled"
	TextServicesManagerService_NewSpellCheckerSession4_FullMethodName    = "/textservice.TextServicesManagerService/NewSpellCheckerSession4"
	TextServicesManagerService_NewSpellCheckerSession3_1_FullMethodName  = "/textservice.TextServicesManagerService/NewSpellCheckerSession3_1"
)

// TextServicesManagerServiceClient is the client API for TextServicesManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TextServicesManagerServiceClient interface {
	GetCurrentSpellCheckerInfo(ctx context.Context, in *GetCurrentSpellCheckerInfoRequest, opts ...grpc.CallOption) (*GetCurrentSpellCheckerInfoResponse, error)
	IsSpellCheckerEnabled(ctx context.Context, in *IsSpellCheckerEnabledRequest, opts ...grpc.CallOption) (*IsSpellCheckerEnabledResponse, error)
	NewSpellCheckerSession4(ctx context.Context, in *NewSpellCheckerSession4Request, opts ...grpc.CallOption) (*NewSpellCheckerSession4Response, error)
	NewSpellCheckerSession3_1(ctx context.Context, in *NewSpellCheckerSession3_1Request, opts ...grpc.CallOption) (*NewSpellCheckerSession3_1Response, error)
}

type textServicesManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTextServicesManagerServiceClient(cc grpc.ClientConnInterface) TextServicesManagerServiceClient {
	return &textServicesManagerServiceClient{cc}
}

func (c *textServicesManagerServiceClient) GetCurrentSpellCheckerInfo(ctx context.Context, in *GetCurrentSpellCheckerInfoRequest, opts ...grpc.CallOption) (*GetCurrentSpellCheckerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentSpellCheckerInfoResponse)
	err := c.cc.Invoke(ctx, TextServicesManagerService_GetCurrentSpellCheckerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *textServicesManagerServiceClient) IsSpellCheckerEnabled(ctx context.Context, in *IsSpellCheckerEnabledRequest, opts ...grpc.CallOption) (*IsSpellCheckerEnabledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsSpellCheckerEnabledResponse)
	err := c.cc.Invoke(ctx, TextServicesManagerService_IsSpellCheckerEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *textServicesManagerServiceClient) NewSpellCheckerSession4(ctx context.Context, in *NewSpellCheckerSession4Request, opts ...grpc.CallOption) (*NewSpellCheckerSession4Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewSpellCheckerSession4Response)
	err := c.cc.Invoke(ctx, TextServicesManagerService_NewSpellCheckerSession4_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *textServicesManagerServiceClient) NewSpellCheckerSession3_1(ctx context.Context, in *NewSpellCheckerSession3_1Request, opts ...grpc.CallOption) (*NewSpellCheckerSession3_1Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewSpellCheckerSession3_1Response)
	err := c.cc.Invoke(ctx, TextServicesManagerService_NewSpellCheckerSession3_1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TextServicesManagerServiceServer is the server API for TextServicesManagerService service.
// All implementations must embed UnimplementedTextServicesManagerServiceServer
// for forward compatibility.
type TextServicesManagerServiceServer interface {
	GetCurrentSpellCheckerInfo(context.Context, *GetCurrentSpellCheckerInfoRequest) (*GetCurrentSpellCheckerInfoResponse, error)
	IsSpellCheckerEnabled(context.Context, *IsSpellCheckerEnabledRequest) (*IsSpellCheckerEnabledResponse, error)
	NewSpellCheckerSession4(context.Context, *NewSpellCheckerSession4Request) (*NewSpellCheckerSession4Response, error)
	NewSpellCheckerSession3_1(context.Context, *NewSpellCheckerSession3_1Request) (*NewSpellCheckerSession3_1Response, error)
	mustEmbedUnimplementedTextServicesManagerServiceServer()
}

// UnimplementedTextServicesManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTextServicesManagerServiceServer struct{}

func (UnimplementedTextServicesManagerServiceServer) GetCurrentSpellCheckerInfo(context.Context, *GetCurrentSpellCheckerInfoRequest) (*GetCurrentSpellCheckerInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentSpellCheckerInfo not implemented")
}
func (UnimplementedTextServicesManagerServiceServer) IsSpellCheckerEnabled(context.Context, *IsSpellCheckerEnabledRequest) (*IsSpellCheckerEnabledResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsSpellCheckerEnabled not implemented")
}
func (UnimplementedTextServicesManagerServiceServer) NewSpellCheckerSession4(context.Context, *NewSpellCheckerSession4Request) (*NewSpellCheckerSession4Response, error) {
	return nil, status.Error(codes.Unimplemented, "method NewSpellCheckerSession4 not implemented")
}
func (UnimplementedTextServicesManagerServiceServer) NewSpellCheckerSession3_1(context.Context, *NewSpellCheckerSession3_1Request) (*NewSpellCheckerSession3_1Response, error) {
	return nil, status.Error(codes.Unimplemented, "method NewSpellCheckerSession3_1 not implemented")
}
func (UnimplementedTextServicesManagerServiceServer) mustEmbedUnimplementedTextServicesManagerServiceServer() {
}
func (UnimplementedTextServicesManagerServiceServer) testEmbeddedByValue() {}

// UnsafeTextServicesManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TextServicesManagerServiceServer will
// result in compilation errors.
type UnsafeTextServicesManagerServiceServer interface {
	mustEmbedUnimplementedTextServicesManagerServiceServer()
}

func RegisterTextServicesManagerServiceServer(s grpc.ServiceRegistrar, srv TextServicesManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedTextServicesManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TextServicesManagerService_ServiceDesc, srv)
}

func _TextServicesManagerService_GetCurrentSpellCheckerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentSpellCheckerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextServicesManagerServiceServer).GetCurrentSpellCheckerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextServicesManagerService_GetCurrentSpellCheckerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextServicesManagerServiceServer).GetCurrentSpellCheckerInfo(ctx, req.(*GetCurrentSpellCheckerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TextServicesManagerService_IsSpellCheckerEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsSpellCheckerEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextServicesManagerServiceServer).IsSpellCheckerEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextServicesManagerService_IsSpellCheckerEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextServicesManagerServiceServer).IsSpellCheckerEnabled(ctx, req.(*IsSpellCheckerEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TextServicesManagerService_NewSpellCheckerSession4_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewSpellCheckerSession4Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextServicesManagerServiceServer).NewSpellCheckerSession4(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextServicesManagerService_NewSpellCheckerSession4_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextServicesManagerServiceServer).NewSpellCheckerSession4(ctx, req.(*NewSpellCheckerSession4Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _TextServicesManagerService_NewSpellCheckerSession3_1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewSpellCheckerSession3_1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextServicesManagerServiceServer).NewSpellCheckerSession3_1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextServicesManagerService_NewSpellCheckerSession3_1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextServicesManagerServiceServer).NewSpellCheckerSession3_1(ctx, req.(*NewSpellCheckerSession3_1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// TextServicesManagerService_ServiceDesc is the grpc.ServiceDesc for TextServicesManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TextServicesManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "textservice.TextServicesManagerService",
	HandlerType: (*TextServicesManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentSpellCheckerInfo",
			Handler:    _TextServicesManagerService_GetCurrentSpellCheckerInfo_Handler,
		},
		{
			MethodName: "IsSpellCheckerEnabled",
			Handler:    _TextServicesManagerService_IsSpellCheckerEnabled_Handler,
		},
		{
			MethodName: "NewSpellCheckerSession4",
			Handler:    _TextServicesManagerService_NewSpellCheckerSession4_Handler,
		},
		{
			MethodName: "NewSpellCheckerSession3_1",
			Handler:    _TextServicesManagerService_NewSpellCheckerSession3_1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/textservice/textservice.proto",
}
