// Code generated by grpcgen. DO NOT EDIT.

package inputmethodservice

import (
	"context"

	"github.com/AndroidGoLab/jni"

	"github.com/AndroidGoLab/jni-proxy/handlestore"
	pb "github.com/AndroidGoLab/jni-proxy/proto/inputmethodservice"
	"github.com/AndroidGoLab/jni/app"
	jnipkg "github.com/AndroidGoLab/jni/inputmethodservice"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// KeyboardServer implements pb.KeyboardServiceServer.
type KeyboardServer struct {
	pb.UnimplementedKeyboardServiceServer
	Ctx     *app.Context
	Handles *handlestore.HandleStore
}

func (s *KeyboardServer) NewKeyboard(_ context.Context, req *pb.NewKeyboardRequest) (*pb.NewKeyboardResponse, error) {
	obj, err := jnipkg.NewKeyboard(s.Ctx.VM, s.Ctx.Obj, req.GetArg1())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create object: %v", err)
	}
	var handle int64
	if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
		handle = s.Handles.Put(env, obj.Obj)
		return nil
	}); doErr != nil {
		return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
	}
	return &pb.NewKeyboardResponse{Result: handle}, nil
}

func (s *KeyboardServer) GetHeight(_ context.Context, req *pb.GetHeightRequest) (*pb.GetHeightResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.Keyboard{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetHeight()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetHeightResponse{Result: result}, nil
}

func (s *KeyboardServer) GetMinWidth(_ context.Context, req *pb.GetMinWidthRequest) (*pb.GetMinWidthResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.Keyboard{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetMinWidth()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetMinWidthResponse{Result: result}, nil
}

func (s *KeyboardServer) GetNearestKeys(_ context.Context, req *pb.GetNearestKeysRequest) (*pb.GetNearestKeysResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.Keyboard{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetNearestKeys(req.GetArg0(), req.GetArg1())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetNearestKeysResponse{Result: handle}, nil
}

func (s *KeyboardServer) GetShiftKeyIndex(_ context.Context, req *pb.GetShiftKeyIndexRequest) (*pb.GetShiftKeyIndexResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.Keyboard{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetShiftKeyIndex()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetShiftKeyIndexResponse{Result: result}, nil
}

func (s *KeyboardServer) IsShifted(_ context.Context, req *pb.IsShiftedRequest) (*pb.IsShiftedResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.Keyboard{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.IsShifted()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsShiftedResponse{Result: result}, nil
}

func (s *KeyboardServer) SetShifted(_ context.Context, req *pb.SetShiftedRequest) (*pb.SetShiftedResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.Keyboard{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.SetShifted(req.GetArg0())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetShiftedResponse{Result: result}, nil
}

// InputMethodServiceServer implements pb.InputMethodServiceServiceServer.
type InputMethodServiceServer struct {
	pb.UnimplementedInputMethodServiceServiceServer
	Ctx     *app.Context
	Handles *handlestore.HandleStore
}

func (s *InputMethodServiceServer) NewInputMethodService(_ context.Context, req *pb.NewInputMethodServiceRequest) (*pb.NewInputMethodServiceResponse, error) {
	obj, err := jnipkg.NewInputMethodService(s.Ctx.VM)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create object: %v", err)
	}
	var handle int64
	if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
		handle = s.Handles.Put(env, obj.Obj)
		return nil
	}); doErr != nil {
		return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
	}
	return &pb.NewInputMethodServiceResponse{Result: handle}, nil
}

func (s *InputMethodServiceServer) EnableHardwareAcceleration(_ context.Context, req *pb.EnableHardwareAccelerationRequest) (*pb.EnableHardwareAccelerationResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.EnableHardwareAcceleration()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.EnableHardwareAccelerationResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) FinishConnectionlessStylusHandwriting(_ context.Context, req *pb.FinishConnectionlessStylusHandwritingRequest) (*pb.FinishConnectionlessStylusHandwritingResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.FinishConnectionlessStylusHandwriting(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.FinishConnectionlessStylusHandwritingResponse{}, nil
}

func (s *InputMethodServiceServer) FinishStylusHandwriting(_ context.Context, req *pb.FinishStylusHandwritingRequest) (*pb.FinishStylusHandwritingResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.FinishStylusHandwriting(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.FinishStylusHandwritingResponse{}, nil
}

func (s *InputMethodServiceServer) GetBackDisposition(_ context.Context, req *pb.GetBackDispositionRequest) (*pb.GetBackDispositionResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetBackDisposition()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetBackDispositionResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) GetCandidatesHiddenVisibility(_ context.Context, req *pb.GetCandidatesHiddenVisibilityRequest) (*pb.GetCandidatesHiddenVisibilityResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetCandidatesHiddenVisibility()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetCandidatesHiddenVisibilityResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) GetCurrentInputBinding(_ context.Context, req *pb.GetCurrentInputBindingRequest) (*pb.GetCurrentInputBindingResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetCurrentInputBinding()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetCurrentInputBindingResponse{Result: handle}, nil
}

func (s *InputMethodServiceServer) GetCurrentInputConnection(_ context.Context, req *pb.GetCurrentInputConnectionRequest) (*pb.GetCurrentInputConnectionResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetCurrentInputConnection()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetCurrentInputConnectionResponse{Result: handle}, nil
}

func (s *InputMethodServiceServer) GetCurrentInputEditorInfo(_ context.Context, req *pb.GetCurrentInputEditorInfoRequest) (*pb.GetCurrentInputEditorInfoResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetCurrentInputEditorInfo()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetCurrentInputEditorInfoResponse{Result: handle}, nil
}

func (s *InputMethodServiceServer) GetCurrentInputStarted(_ context.Context, req *pb.GetCurrentInputStartedRequest) (*pb.GetCurrentInputStartedResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetCurrentInputStarted()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetCurrentInputStartedResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) GetInputMethodWindowRecommendedHeight(_ context.Context, req *pb.GetInputMethodWindowRecommendedHeightRequest) (*pb.GetInputMethodWindowRecommendedHeightResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetInputMethodWindowRecommendedHeight()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetInputMethodWindowRecommendedHeightResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) GetLayoutInflater(_ context.Context, req *pb.GetLayoutInflaterRequest) (*pb.GetLayoutInflaterResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetLayoutInflater()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetLayoutInflaterResponse{Result: handle}, nil
}

func (s *InputMethodServiceServer) GetMaxWidth(_ context.Context, req *pb.GetMaxWidthRequest) (*pb.GetMaxWidthResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetMaxWidth()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.GetMaxWidthResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) GetStylusHandwritingSessionTimeout(_ context.Context, req *pb.GetStylusHandwritingSessionTimeoutRequest) (*pb.GetStylusHandwritingSessionTimeoutResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetStylusHandwritingSessionTimeout()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetStylusHandwritingSessionTimeoutResponse{Result: handle}, nil
}

func (s *InputMethodServiceServer) GetStylusHandwritingWindow(_ context.Context, req *pb.GetStylusHandwritingWindowRequest) (*pb.GetStylusHandwritingWindowResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetStylusHandwritingWindow()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetStylusHandwritingWindowResponse{Result: handle}, nil
}

func (s *InputMethodServiceServer) GetSystemService(_ context.Context, req *pb.InputMethodServiceGetSystemServiceRequest) (*pb.GetSystemServiceResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetSystemService(req.GetArg0())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetSystemServiceResponse{Result: handle}, nil
}

func (s *InputMethodServiceServer) GetTextForImeAction(_ context.Context, req *pb.GetTextForImeActionRequest) (*pb.GetTextForImeActionResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetTextForImeAction(req.GetArg0())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetTextForImeActionResponse{Result: handle}, nil
}

func (s *InputMethodServiceServer) GetWindow(_ context.Context, req *pb.GetWindowRequest) (*pb.GetWindowResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetWindow()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetWindowResponse{Result: handle}, nil
}

func (s *InputMethodServiceServer) HideStatusIcon(_ context.Context, req *pb.HideStatusIconRequest) (*pb.HideStatusIconResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.HideStatusIcon(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.HideStatusIconResponse{}, nil
}

func (s *InputMethodServiceServer) HideWindow(_ context.Context, req *pb.HideWindowRequest) (*pb.HideWindowResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.HideWindow(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.HideWindowResponse{}, nil
}

func (s *InputMethodServiceServer) IsExtractViewShown(_ context.Context, req *pb.IsExtractViewShownRequest) (*pb.IsExtractViewShownResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.IsExtractViewShown()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsExtractViewShownResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) IsFullscreenMode(_ context.Context, req *pb.IsFullscreenModeRequest) (*pb.IsFullscreenModeResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.IsFullscreenMode()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsFullscreenModeResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) IsInputViewShown(_ context.Context, req *pb.IsInputViewShownRequest) (*pb.IsInputViewShownResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.IsInputViewShown()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsInputViewShownResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) IsShowInputRequested(_ context.Context, req *pb.IsShowInputRequestedRequest) (*pb.IsShowInputRequestedResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.IsShowInputRequested()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsShowInputRequestedResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) OnAppPrivateCommand(_ context.Context, req *pb.OnAppPrivateCommandRequest) (*pb.OnAppPrivateCommandResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnAppPrivateCommand(req.GetArg0(), s.Handles.Get(req.GetArg1())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnAppPrivateCommandResponse{}, nil
}

func (s *InputMethodServiceServer) OnBindInput(_ context.Context, req *pb.OnBindInputRequest) (*pb.OnBindInputResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnBindInput(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnBindInputResponse{}, nil
}

func (s *InputMethodServiceServer) OnComputeInsets(_ context.Context, req *pb.OnComputeInsetsRequest) (*pb.OnComputeInsetsResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnComputeInsets(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnComputeInsetsResponse{}, nil
}

func (s *InputMethodServiceServer) OnConfigurationChanged(_ context.Context, req *pb.InputMethodServiceOnConfigurationChangedRequest) (*pb.OnConfigurationChangedResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnConfigurationChanged(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnConfigurationChangedResponse{}, nil
}

func (s *InputMethodServiceServer) OnConfigureWindow(_ context.Context, req *pb.OnConfigureWindowRequest) (*pb.OnConfigureWindowResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnConfigureWindow(s.Handles.Get(req.GetArg0()), req.GetArg1(), req.GetArg2()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnConfigureWindowResponse{}, nil
}

func (s *InputMethodServiceServer) OnCreate(_ context.Context, req *pb.OnCreateRequest) (*pb.OnCreateResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnCreate(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnCreateResponse{}, nil
}

func (s *InputMethodServiceServer) OnCreateCandidatesView(_ context.Context, req *pb.OnCreateCandidatesViewRequest) (*pb.OnCreateCandidatesViewResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.OnCreateCandidatesView()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.OnCreateCandidatesViewResponse{Result: handle}, nil
}

func (s *InputMethodServiceServer) OnCreateExtractTextView(_ context.Context, req *pb.OnCreateExtractTextViewRequest) (*pb.OnCreateExtractTextViewResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.OnCreateExtractTextView()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.OnCreateExtractTextViewResponse{Result: handle}, nil
}

func (s *InputMethodServiceServer) OnCreateInlineSuggestionsRequest(_ context.Context, req *pb.OnCreateInlineSuggestionsRequestRequest) (*pb.OnCreateInlineSuggestionsRequestResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.OnCreateInlineSuggestionsRequest(s.Handles.Get(req.GetArg0()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.OnCreateInlineSuggestionsRequestResponse{Result: handle}, nil
}

func (s *InputMethodServiceServer) OnCreateInputMethodInterface(_ context.Context, req *pb.InputMethodServiceOnCreateInputMethodInterfaceRequest) (*pb.OnCreateInputMethodInterfaceResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.OnCreateInputMethodInterface()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.OnCreateInputMethodInterfaceResponse{Result: handle}, nil
}

func (s *InputMethodServiceServer) OnCreateInputMethodSessionInterface(_ context.Context, req *pb.InputMethodServiceOnCreateInputMethodSessionInterfaceRequest) (*pb.OnCreateInputMethodSessionInterfaceResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.OnCreateInputMethodSessionInterface()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.OnCreateInputMethodSessionInterfaceResponse{Result: handle}, nil
}

func (s *InputMethodServiceServer) OnCreateInputView(_ context.Context, req *pb.OnCreateInputViewRequest) (*pb.OnCreateInputViewResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.OnCreateInputView()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.OnCreateInputViewResponse{Result: handle}, nil
}

func (s *InputMethodServiceServer) OnCustomImeSwitcherButtonRequestedVisible(_ context.Context, req *pb.OnCustomImeSwitcherButtonRequestedVisibleRequest) (*pb.OnCustomImeSwitcherButtonRequestedVisibleResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnCustomImeSwitcherButtonRequestedVisible(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnCustomImeSwitcherButtonRequestedVisibleResponse{}, nil
}

func (s *InputMethodServiceServer) OnDestroy(_ context.Context, req *pb.InputMethodServiceOnDestroyRequest) (*pb.OnDestroyResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnDestroy(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnDestroyResponse{}, nil
}

func (s *InputMethodServiceServer) OnDisplayCompletions(_ context.Context, req *pb.OnDisplayCompletionsRequest) (*pb.OnDisplayCompletionsResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnDisplayCompletions(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnDisplayCompletionsResponse{}, nil
}

func (s *InputMethodServiceServer) OnEvaluateFullscreenMode(_ context.Context, req *pb.OnEvaluateFullscreenModeRequest) (*pb.OnEvaluateFullscreenModeResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.OnEvaluateFullscreenMode()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnEvaluateFullscreenModeResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) OnEvaluateInputViewShown(_ context.Context, req *pb.OnEvaluateInputViewShownRequest) (*pb.OnEvaluateInputViewShownResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.OnEvaluateInputViewShown()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnEvaluateInputViewShownResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) OnExtractTextContextMenuItem(_ context.Context, req *pb.OnExtractTextContextMenuItemRequest) (*pb.OnExtractTextContextMenuItemResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.OnExtractTextContextMenuItem(req.GetArg0())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnExtractTextContextMenuItemResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) OnExtractedCursorMovement(_ context.Context, req *pb.OnExtractedCursorMovementRequest) (*pb.OnExtractedCursorMovementResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnExtractedCursorMovement(req.GetArg0(), req.GetArg1()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnExtractedCursorMovementResponse{}, nil
}

func (s *InputMethodServiceServer) OnExtractedSelectionChanged(_ context.Context, req *pb.OnExtractedSelectionChangedRequest) (*pb.OnExtractedSelectionChangedResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnExtractedSelectionChanged(req.GetArg0(), req.GetArg1()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnExtractedSelectionChangedResponse{}, nil
}

func (s *InputMethodServiceServer) OnExtractedTextClicked(_ context.Context, req *pb.OnExtractedTextClickedRequest) (*pb.OnExtractedTextClickedResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnExtractedTextClicked(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnExtractedTextClickedResponse{}, nil
}

func (s *InputMethodServiceServer) OnExtractingInputChanged(_ context.Context, req *pb.OnExtractingInputChangedRequest) (*pb.OnExtractingInputChangedResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnExtractingInputChanged(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnExtractingInputChangedResponse{}, nil
}

func (s *InputMethodServiceServer) OnFinishCandidatesView(_ context.Context, req *pb.OnFinishCandidatesViewRequest) (*pb.OnFinishCandidatesViewResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnFinishCandidatesView(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnFinishCandidatesViewResponse{}, nil
}

func (s *InputMethodServiceServer) OnFinishInput(_ context.Context, req *pb.OnFinishInputRequest) (*pb.OnFinishInputResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnFinishInput(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnFinishInputResponse{}, nil
}

func (s *InputMethodServiceServer) OnFinishInputView(_ context.Context, req *pb.OnFinishInputViewRequest) (*pb.OnFinishInputViewResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnFinishInputView(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnFinishInputViewResponse{}, nil
}

func (s *InputMethodServiceServer) OnFinishStylusHandwriting(_ context.Context, req *pb.OnFinishStylusHandwritingRequest) (*pb.OnFinishStylusHandwritingResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnFinishStylusHandwriting(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnFinishStylusHandwritingResponse{}, nil
}

func (s *InputMethodServiceServer) OnGenericMotionEvent(_ context.Context, req *pb.InputMethodServiceOnGenericMotionEventRequest) (*pb.OnGenericMotionEventResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.OnGenericMotionEvent(s.Handles.Get(req.GetArg0()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnGenericMotionEventResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) OnInitializeInterface(_ context.Context, req *pb.OnInitializeInterfaceRequest) (*pb.OnInitializeInterfaceResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnInitializeInterface(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnInitializeInterfaceResponse{}, nil
}

func (s *InputMethodServiceServer) OnInlineSuggestionsResponse(_ context.Context, req *pb.OnInlineSuggestionsResponseRequest) (*pb.OnInlineSuggestionsResponseResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.OnInlineSuggestionsResponse(s.Handles.Get(req.GetArg0()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnInlineSuggestionsResponseResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) OnKeyDown(_ context.Context, req *pb.OnKeyDownRequest) (*pb.OnKeyDownResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.OnKeyDown(req.GetArg0(), s.Handles.Get(req.GetArg1()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnKeyDownResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) OnKeyLongPress(_ context.Context, req *pb.OnKeyLongPressRequest) (*pb.OnKeyLongPressResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.OnKeyLongPress(req.GetArg0(), s.Handles.Get(req.GetArg1()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnKeyLongPressResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) OnKeyMultiple(_ context.Context, req *pb.OnKeyMultipleRequest) (*pb.OnKeyMultipleResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.OnKeyMultiple(req.GetArg0(), req.GetArg1(), s.Handles.Get(req.GetArg2()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnKeyMultipleResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) OnKeyUp(_ context.Context, req *pb.OnKeyUpRequest) (*pb.OnKeyUpResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.OnKeyUp(req.GetArg0(), s.Handles.Get(req.GetArg1()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnKeyUpResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) OnPrepareStylusHandwriting(_ context.Context, req *pb.OnPrepareStylusHandwritingRequest) (*pb.OnPrepareStylusHandwritingResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnPrepareStylusHandwriting(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnPrepareStylusHandwritingResponse{}, nil
}

func (s *InputMethodServiceServer) OnShouldVerifyKeyEvent(_ context.Context, req *pb.InputMethodServiceOnShouldVerifyKeyEventRequest) (*pb.OnShouldVerifyKeyEventResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.OnShouldVerifyKeyEvent(s.Handles.Get(req.GetArg0()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnShouldVerifyKeyEventResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) OnShowInputRequested(_ context.Context, req *pb.OnShowInputRequestedRequest) (*pb.OnShowInputRequestedResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.OnShowInputRequested(req.GetArg0(), req.GetArg1())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnShowInputRequestedResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) OnStartCandidatesView(_ context.Context, req *pb.OnStartCandidatesViewRequest) (*pb.OnStartCandidatesViewResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnStartCandidatesView(s.Handles.Get(req.GetArg0()), req.GetArg1()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnStartCandidatesViewResponse{}, nil
}

func (s *InputMethodServiceServer) OnStartConnectionlessStylusHandwriting(_ context.Context, req *pb.OnStartConnectionlessStylusHandwritingRequest) (*pb.OnStartConnectionlessStylusHandwritingResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.OnStartConnectionlessStylusHandwriting(req.GetArg0(), s.Handles.Get(req.GetArg1()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnStartConnectionlessStylusHandwritingResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) OnStartInput(_ context.Context, req *pb.OnStartInputRequest) (*pb.OnStartInputResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnStartInput(s.Handles.Get(req.GetArg0()), req.GetArg1()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnStartInputResponse{}, nil
}

func (s *InputMethodServiceServer) OnStartInputView(_ context.Context, req *pb.OnStartInputViewRequest) (*pb.OnStartInputViewResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnStartInputView(s.Handles.Get(req.GetArg0()), req.GetArg1()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnStartInputViewResponse{}, nil
}

func (s *InputMethodServiceServer) OnStartStylusHandwriting(_ context.Context, req *pb.OnStartStylusHandwritingRequest) (*pb.OnStartStylusHandwritingResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.OnStartStylusHandwriting()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnStartStylusHandwritingResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) OnStylusHandwritingMotionEvent(_ context.Context, req *pb.OnStylusHandwritingMotionEventRequest) (*pb.OnStylusHandwritingMotionEventResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnStylusHandwritingMotionEvent(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnStylusHandwritingMotionEventResponse{}, nil
}

func (s *InputMethodServiceServer) OnTrackballEvent(_ context.Context, req *pb.InputMethodServiceOnTrackballEventRequest) (*pb.OnTrackballEventResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.OnTrackballEvent(s.Handles.Get(req.GetArg0()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnTrackballEventResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) OnUnbindInput(_ context.Context, req *pb.OnUnbindInputRequest) (*pb.OnUnbindInputResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnUnbindInput(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnUnbindInputResponse{}, nil
}

func (s *InputMethodServiceServer) OnUpdateCursor(_ context.Context, req *pb.OnUpdateCursorRequest) (*pb.OnUpdateCursorResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnUpdateCursor(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnUpdateCursorResponse{}, nil
}

func (s *InputMethodServiceServer) OnUpdateCursorAnchorInfo(_ context.Context, req *pb.OnUpdateCursorAnchorInfoRequest) (*pb.OnUpdateCursorAnchorInfoResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnUpdateCursorAnchorInfo(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnUpdateCursorAnchorInfoResponse{}, nil
}

func (s *InputMethodServiceServer) OnUpdateEditorToolType(_ context.Context, req *pb.OnUpdateEditorToolTypeRequest) (*pb.OnUpdateEditorToolTypeResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnUpdateEditorToolType(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnUpdateEditorToolTypeResponse{}, nil
}

func (s *InputMethodServiceServer) OnUpdateExtractedText(_ context.Context, req *pb.OnUpdateExtractedTextRequest) (*pb.OnUpdateExtractedTextResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnUpdateExtractedText(req.GetArg0(), s.Handles.Get(req.GetArg1())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnUpdateExtractedTextResponse{}, nil
}

func (s *InputMethodServiceServer) OnUpdateExtractingViews(_ context.Context, req *pb.OnUpdateExtractingViewsRequest) (*pb.OnUpdateExtractingViewsResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnUpdateExtractingViews(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnUpdateExtractingViewsResponse{}, nil
}

func (s *InputMethodServiceServer) OnUpdateExtractingVisibility(_ context.Context, req *pb.OnUpdateExtractingVisibilityRequest) (*pb.OnUpdateExtractingVisibilityResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnUpdateExtractingVisibility(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnUpdateExtractingVisibilityResponse{}, nil
}

func (s *InputMethodServiceServer) OnUpdateSelection(_ context.Context, req *pb.OnUpdateSelectionRequest) (*pb.OnUpdateSelectionResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnUpdateSelection(req.GetArg0(), req.GetArg1(), req.GetArg2(), req.GetArg3(), req.GetArg4(), req.GetArg5()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnUpdateSelectionResponse{}, nil
}

func (s *InputMethodServiceServer) OnViewClicked(_ context.Context, req *pb.OnViewClickedRequest) (*pb.OnViewClickedResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnViewClicked(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnViewClickedResponse{}, nil
}

func (s *InputMethodServiceServer) OnWindowHidden(_ context.Context, req *pb.OnWindowHiddenRequest) (*pb.OnWindowHiddenResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnWindowHidden(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnWindowHiddenResponse{}, nil
}

func (s *InputMethodServiceServer) OnWindowShown(_ context.Context, req *pb.OnWindowShownRequest) (*pb.OnWindowShownResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnWindowShown(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnWindowShownResponse{}, nil
}

func (s *InputMethodServiceServer) RequestHideSelf(_ context.Context, req *pb.RequestHideSelfRequest) (*pb.RequestHideSelfResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.RequestHideSelf(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.RequestHideSelfResponse{}, nil
}

func (s *InputMethodServiceServer) RequestShowSelf(_ context.Context, req *pb.RequestShowSelfRequest) (*pb.RequestShowSelfResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.RequestShowSelf(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.RequestShowSelfResponse{}, nil
}

func (s *InputMethodServiceServer) SendDefaultEditorAction(_ context.Context, req *pb.SendDefaultEditorActionRequest) (*pb.SendDefaultEditorActionResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.SendDefaultEditorAction(req.GetArg0())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SendDefaultEditorActionResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) SendDownUpKeyEvents(_ context.Context, req *pb.SendDownUpKeyEventsRequest) (*pb.SendDownUpKeyEventsResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.SendDownUpKeyEvents(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SendDownUpKeyEventsResponse{}, nil
}

func (s *InputMethodServiceServer) SendKeyChar(_ context.Context, req *pb.SendKeyCharRequest) (*pb.SendKeyCharResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.SendKeyChar(uint16(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SendKeyCharResponse{}, nil
}

func (s *InputMethodServiceServer) SetBackDisposition(_ context.Context, req *pb.SetBackDispositionRequest) (*pb.SetBackDispositionResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.SetBackDisposition(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetBackDispositionResponse{}, nil
}

func (s *InputMethodServiceServer) SetCandidatesView(_ context.Context, req *pb.SetCandidatesViewRequest) (*pb.SetCandidatesViewResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.SetCandidatesView(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetCandidatesViewResponse{}, nil
}

func (s *InputMethodServiceServer) SetCandidatesViewShown(_ context.Context, req *pb.SetCandidatesViewShownRequest) (*pb.SetCandidatesViewShownResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.SetCandidatesViewShown(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetCandidatesViewShownResponse{}, nil
}

func (s *InputMethodServiceServer) SetExtractView(_ context.Context, req *pb.SetExtractViewRequest) (*pb.SetExtractViewResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.SetExtractView(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetExtractViewResponse{}, nil
}

func (s *InputMethodServiceServer) SetExtractViewShown(_ context.Context, req *pb.SetExtractViewShownRequest) (*pb.SetExtractViewShownResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.SetExtractViewShown(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetExtractViewShownResponse{}, nil
}

func (s *InputMethodServiceServer) SetInputView(_ context.Context, req *pb.SetInputViewRequest) (*pb.SetInputViewResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.SetInputView(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetInputViewResponse{}, nil
}

func (s *InputMethodServiceServer) SetStylusHandwritingRegion(_ context.Context, req *pb.SetStylusHandwritingRegionRequest) (*pb.SetStylusHandwritingRegionResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.SetStylusHandwritingRegion(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetStylusHandwritingRegionResponse{}, nil
}

func (s *InputMethodServiceServer) SetStylusHandwritingSessionTimeout(_ context.Context, req *pb.SetStylusHandwritingSessionTimeoutRequest) (*pb.SetStylusHandwritingSessionTimeoutResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.SetStylusHandwritingSessionTimeout(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetStylusHandwritingSessionTimeoutResponse{}, nil
}

func (s *InputMethodServiceServer) SetTheme(_ context.Context, req *pb.SetThemeRequest) (*pb.SetThemeResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.SetTheme(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetThemeResponse{}, nil
}

func (s *InputMethodServiceServer) ShouldOfferSwitchingToNextInputMethod(_ context.Context, req *pb.ShouldOfferSwitchingToNextInputMethodRequest) (*pb.ShouldOfferSwitchingToNextInputMethodResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.ShouldOfferSwitchingToNextInputMethod()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.ShouldOfferSwitchingToNextInputMethodResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) ShowStatusIcon(_ context.Context, req *pb.ShowStatusIconRequest) (*pb.ShowStatusIconResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.ShowStatusIcon(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.ShowStatusIconResponse{}, nil
}

func (s *InputMethodServiceServer) ShowWindow(_ context.Context, req *pb.ShowWindowRequest) (*pb.ShowWindowResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.ShowWindow(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.ShowWindowResponse{}, nil
}

func (s *InputMethodServiceServer) SwitchInputMethod1(_ context.Context, req *pb.SwitchInputMethod1Request) (*pb.SwitchInputMethod1Response, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.SwitchInputMethod1(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SwitchInputMethod1Response{}, nil
}

func (s *InputMethodServiceServer) SwitchInputMethod2_1(_ context.Context, req *pb.SwitchInputMethod2_1Request) (*pb.SwitchInputMethod2_1Response, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.SwitchInputMethod2_1(req.GetArg0(), s.Handles.Get(req.GetArg1())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SwitchInputMethod2_1Response{}, nil
}

func (s *InputMethodServiceServer) SwitchToNextInputMethod(_ context.Context, req *pb.SwitchToNextInputMethodRequest) (*pb.SwitchToNextInputMethodResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.SwitchToNextInputMethod(req.GetArg0())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SwitchToNextInputMethodResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) SwitchToPreviousInputMethod(_ context.Context, req *pb.SwitchToPreviousInputMethodRequest) (*pb.SwitchToPreviousInputMethodResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.SwitchToPreviousInputMethod()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SwitchToPreviousInputMethodResponse{Result: result}, nil
}

func (s *InputMethodServiceServer) UpdateFullscreenMode(_ context.Context, req *pb.UpdateFullscreenModeRequest) (*pb.UpdateFullscreenModeResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.UpdateFullscreenMode(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.UpdateFullscreenModeResponse{}, nil
}

func (s *InputMethodServiceServer) UpdateInputViewShown(_ context.Context, req *pb.UpdateInputViewShownRequest) (*pb.UpdateInputViewShownResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.UpdateInputViewShown(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.UpdateInputViewShownResponse{}, nil
}

func (s *InputMethodServiceServer) GetStylusHandwritingIdleTimeoutMax(_ context.Context, req *pb.GetStylusHandwritingIdleTimeoutMaxRequest) (*pb.GetStylusHandwritingIdleTimeoutMaxResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.InputMethodService{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetStylusHandwritingIdleTimeoutMax()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetStylusHandwritingIdleTimeoutMaxResponse{Result: handle}, nil
}

// ExtractEditTextServer implements pb.ExtractEditTextServiceServer.
type ExtractEditTextServer struct {
	pb.UnimplementedExtractEditTextServiceServer
	Ctx     *app.Context
	Handles *handlestore.HandleStore
}

func (s *ExtractEditTextServer) NewExtractEditText(_ context.Context, req *pb.NewExtractEditTextRequest) (*pb.NewExtractEditTextResponse, error) {
	obj, err := jnipkg.NewExtractEditText(s.Ctx.VM, s.Ctx.Obj)
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create object: %v", err)
	}
	var handle int64
	if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
		handle = s.Handles.Put(env, obj.Obj)
		return nil
	}); doErr != nil {
		return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
	}
	return &pb.NewExtractEditTextResponse{Result: handle}, nil
}

func (s *ExtractEditTextServer) FinishInternalChanges(_ context.Context, req *pb.FinishInternalChangesRequest) (*pb.FinishInternalChangesResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.ExtractEditText{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.FinishInternalChanges(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.FinishInternalChangesResponse{}, nil
}

func (s *ExtractEditTextServer) HasFocus(_ context.Context, req *pb.HasFocusRequest) (*pb.HasFocusResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.ExtractEditText{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.HasFocus()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.HasFocusResponse{Result: result}, nil
}

func (s *ExtractEditTextServer) HasVerticalScrollBar(_ context.Context, req *pb.HasVerticalScrollBarRequest) (*pb.HasVerticalScrollBarResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.ExtractEditText{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.HasVerticalScrollBar()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.HasVerticalScrollBarResponse{Result: result}, nil
}

func (s *ExtractEditTextServer) HasWindowFocus(_ context.Context, req *pb.HasWindowFocusRequest) (*pb.HasWindowFocusResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.ExtractEditText{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.HasWindowFocus()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.HasWindowFocusResponse{Result: result}, nil
}

func (s *ExtractEditTextServer) IsFocused(_ context.Context, req *pb.IsFocusedRequest) (*pb.IsFocusedResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.ExtractEditText{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.IsFocused()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsFocusedResponse{Result: result}, nil
}

func (s *ExtractEditTextServer) IsInputMethodTarget(_ context.Context, req *pb.IsInputMethodTargetRequest) (*pb.IsInputMethodTargetResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.ExtractEditText{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.IsInputMethodTarget()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsInputMethodTargetResponse{Result: result}, nil
}

func (s *ExtractEditTextServer) OnTextContextMenuItem(_ context.Context, req *pb.OnTextContextMenuItemRequest) (*pb.OnTextContextMenuItemResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.ExtractEditText{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.OnTextContextMenuItem(req.GetArg0())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnTextContextMenuItemResponse{Result: result}, nil
}

func (s *ExtractEditTextServer) PerformClick(_ context.Context, req *pb.PerformClickRequest) (*pb.PerformClickResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.ExtractEditText{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.PerformClick()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.PerformClickResponse{Result: result}, nil
}

func (s *ExtractEditTextServer) SetExtractedText(_ context.Context, req *pb.SetExtractedTextRequest) (*pb.SetExtractedTextResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.ExtractEditText{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.SetExtractedText(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetExtractedTextResponse{}, nil
}

func (s *ExtractEditTextServer) StartInternalChanges(_ context.Context, req *pb.StartInternalChangesRequest) (*pb.StartInternalChangesResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.ExtractEditText{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.StartInternalChanges(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.StartInternalChangesResponse{}, nil
}

// KeyboardViewServer implements pb.KeyboardViewServiceServer.
type KeyboardViewServer struct {
	pb.UnimplementedKeyboardViewServiceServer
	Ctx     *app.Context
	Handles *handlestore.HandleStore
}

func (s *KeyboardViewServer) NewKeyboardView(_ context.Context, req *pb.NewKeyboardViewRequest) (*pb.NewKeyboardViewResponse, error) {
	obj, err := jnipkg.NewKeyboardView(s.Ctx.VM, s.Ctx.Obj, s.Handles.Get(req.GetArg1()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "create object: %v", err)
	}
	var handle int64
	if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
		handle = s.Handles.Put(env, obj.Obj)
		return nil
	}); doErr != nil {
		return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
	}
	return &pb.NewKeyboardViewResponse{Result: handle}, nil
}

func (s *KeyboardViewServer) Closing(_ context.Context, req *pb.ClosingRequest) (*pb.ClosingResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.KeyboardView{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.Closing(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.ClosingResponse{}, nil
}

func (s *KeyboardViewServer) GetKeyboard(_ context.Context, req *pb.GetKeyboardRequest) (*pb.GetKeyboardResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.KeyboardView{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.GetKeyboard()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	var handle int64
	if result != nil {
		if doErr := s.Ctx.VM.Do(func(env *jni.Env) error {
			handle = s.Handles.Put(env, result)
			return nil
		}); doErr != nil {
			return nil, status.Errorf(codes.Internal, "store handle: %v", doErr)
		}
	}
	return &pb.GetKeyboardResponse{Result: handle}, nil
}

func (s *KeyboardViewServer) HandleBack(_ context.Context, req *pb.HandleBackRequest) (*pb.HandleBackResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.KeyboardView{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.HandleBack()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.HandleBackResponse{Result: result}, nil
}

func (s *KeyboardViewServer) InvalidateAllKeys(_ context.Context, req *pb.InvalidateAllKeysRequest) (*pb.InvalidateAllKeysResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.KeyboardView{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.InvalidateAllKeys(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.InvalidateAllKeysResponse{}, nil
}

func (s *KeyboardViewServer) InvalidateKey(_ context.Context, req *pb.InvalidateKeyRequest) (*pb.InvalidateKeyResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.KeyboardView{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.InvalidateKey(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.InvalidateKeyResponse{}, nil
}

func (s *KeyboardViewServer) IsPreviewEnabled(_ context.Context, req *pb.IsPreviewEnabledRequest) (*pb.IsPreviewEnabledResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.KeyboardView{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.IsPreviewEnabled()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsPreviewEnabledResponse{Result: result}, nil
}

func (s *KeyboardViewServer) IsProximityCorrectionEnabled(_ context.Context, req *pb.IsProximityCorrectionEnabledRequest) (*pb.IsProximityCorrectionEnabledResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.KeyboardView{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.IsProximityCorrectionEnabled()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsProximityCorrectionEnabledResponse{Result: result}, nil
}

func (s *KeyboardViewServer) IsShifted(_ context.Context, req *pb.IsShiftedRequest) (*pb.IsShiftedResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.KeyboardView{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.IsShifted()
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.IsShiftedResponse{Result: result}, nil
}

func (s *KeyboardViewServer) OnClick(_ context.Context, req *pb.OnClickRequest) (*pb.OnClickResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.KeyboardView{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnClick(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnClickResponse{}, nil
}

func (s *KeyboardViewServer) OnDetachedFromWindow(_ context.Context, req *pb.OnDetachedFromWindowRequest) (*pb.OnDetachedFromWindowResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.KeyboardView{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnDetachedFromWindow(); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnDetachedFromWindowResponse{}, nil
}

func (s *KeyboardViewServer) OnDraw(_ context.Context, req *pb.OnDrawRequest) (*pb.OnDrawResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.KeyboardView{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnDraw(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnDrawResponse{}, nil
}

func (s *KeyboardViewServer) OnHoverEvent(_ context.Context, req *pb.OnHoverEventRequest) (*pb.OnHoverEventResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.KeyboardView{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.OnHoverEvent(s.Handles.Get(req.GetArg0()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnHoverEventResponse{Result: result}, nil
}

func (s *KeyboardViewServer) OnMeasure(_ context.Context, req *pb.OnMeasureRequest) (*pb.OnMeasureResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.KeyboardView{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnMeasure(req.GetArg0(), req.GetArg1()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnMeasureResponse{}, nil
}

func (s *KeyboardViewServer) OnSizeChanged(_ context.Context, req *pb.OnSizeChangedRequest) (*pb.OnSizeChangedResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.KeyboardView{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.OnSizeChanged(req.GetArg0(), req.GetArg1(), req.GetArg2(), req.GetArg3()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnSizeChangedResponse{}, nil
}

func (s *KeyboardViewServer) OnTouchEvent(_ context.Context, req *pb.OnTouchEventRequest) (*pb.OnTouchEventResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.KeyboardView{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.OnTouchEvent(s.Handles.Get(req.GetArg0()))
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.OnTouchEventResponse{Result: result}, nil
}

func (s *KeyboardViewServer) SetKeyboard(_ context.Context, req *pb.SetKeyboardRequest) (*pb.SetKeyboardResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.KeyboardView{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.SetKeyboard(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetKeyboardResponse{}, nil
}

func (s *KeyboardViewServer) SetOnKeyboardActionListener(_ context.Context, req *pb.SetOnKeyboardActionListenerRequest) (*pb.SetOnKeyboardActionListenerResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.KeyboardView{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.SetOnKeyboardActionListener(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetOnKeyboardActionListenerResponse{}, nil
}

func (s *KeyboardViewServer) SetPopupOffset(_ context.Context, req *pb.SetPopupOffsetRequest) (*pb.SetPopupOffsetResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.KeyboardView{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.SetPopupOffset(req.GetArg0(), req.GetArg1()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetPopupOffsetResponse{}, nil
}

func (s *KeyboardViewServer) SetPopupParent(_ context.Context, req *pb.SetPopupParentRequest) (*pb.SetPopupParentResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.KeyboardView{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.SetPopupParent(s.Handles.Get(req.GetArg0())); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetPopupParentResponse{}, nil
}

func (s *KeyboardViewServer) SetPreviewEnabled(_ context.Context, req *pb.SetPreviewEnabledRequest) (*pb.SetPreviewEnabledResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.KeyboardView{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.SetPreviewEnabled(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetPreviewEnabledResponse{}, nil
}

func (s *KeyboardViewServer) SetProximityCorrectionEnabled(_ context.Context, req *pb.SetProximityCorrectionEnabledRequest) (*pb.SetProximityCorrectionEnabledResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.KeyboardView{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.SetProximityCorrectionEnabled(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetProximityCorrectionEnabledResponse{}, nil
}

func (s *KeyboardViewServer) SetShifted(_ context.Context, req *pb.SetShiftedRequest) (*pb.SetShiftedResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.KeyboardView{VM: s.Ctx.VM, Obj: rawObj}

	result, err := mgr.SetShifted(req.GetArg0())
	if err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetShiftedResponse{Result: result}, nil
}

func (s *KeyboardViewServer) SetVerticalCorrection(_ context.Context, req *pb.SetVerticalCorrectionRequest) (*pb.SetVerticalCorrectionResponse, error) {
	rawObj := s.Handles.Get(req.GetHandle())
	if rawObj == nil {
		return nil, status.Errorf(codes.InvalidArgument, "invalid handle")
	}
	mgr := &jnipkg.KeyboardView{VM: s.Ctx.VM, Obj: rawObj}

	if err := mgr.SetVerticalCorrection(req.GetArg0()); err != nil {
		return nil, status.Errorf(codes.Internal, "%v", err)
	}
	return &pb.SetVerticalCorrectionResponse{}, nil
}
